// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Common.DataEntites;
using GenSoft.Entities;
using GenSoft.Interfaces;

namespace GenSoft.Entities
{
	public partial class ProcessInfo: BaseEntity, IProcessInfo
	{
		public string UserName { get; set; }
		public string Description { get; set; }
		public string Name { get; set; }
		public int? ParentProcessId { get; set; }
		public string Symbol { get; set; }

	}
}
