// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Common.DataEntites;
using GenSoft.Entities;
using GenSoft.Interfaces;

namespace GenSoft.Entities
{
	public partial class Action: BaseEntity, IAction
	{
		public virtual string Body { get; set; }
		public virtual string Description { get; set; }
		public virtual string Name { get; set; }
		public virtual string ParameterName { get; set; }

		//-------------------Navigation Properties -------------------------------//
			// ---------Child Relationships
				public virtual ICollection<ActionParameters> ActionParameters {get; set;}
				public virtual ICollection<ActionReferenceTypes> ActionReferenceTypes {get; set;}
				public virtual ICollection<ActionSetActions> ActionSetActions {get; set;}
				public virtual ICollection<ProcessAction> ProcessAction {get; set;}
		
			// ---------Parent Relationships
	

	}
}
