// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Common.DataEntites;
using GenSoft.Entities;
using GenSoft.Interfaces;

namespace GenSoft.Entities
{
	public partial class ActionProperties: BaseEntity, IActionProperties
	{
		public virtual int ActionSetId { get; set; }

		//-------------------Navigation Properties -------------------------------//
			// ---------Child Relationships
				public virtual ICollection<ActionParameterConstants> ActionParameterConstants {get; set;}
				public virtual ICollection<ActionPropertyParameter> ActionPropertyParameter {get; set;}
		
			// ---------Parent Relationships
				public virtual EntityTypeAttributes EntityTypeAttributes {get; set;}
				public virtual ActionSet ActionSet {get; set;}
	

	}
}
