// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Common.DataEntites;
using GenSoft.Entities;
using GenSoft.Interfaces;

namespace GenSoft.Entities
{
	public partial class Customs_Procedure: BaseEntity, ICustoms_Procedure
	{
		public virtual int DocumentTypeId { get; set; }
		public virtual int ExtendedCustomsProcedureId { get; set; }
		public virtual int NationalCustomsProcedureId { get; set; }

		//-------------------Navigation Properties -------------------------------//
			// ---------Child Relationships
				public virtual ICollection<xcuda_ASYCUDA_ExtendedProperties> xcuda_ASYCUDA_ExtendedProperties {get; set;}
				public virtual DefaultCustomsProcedure DefaultCustomsProcedure {get; set;}
		
			// ---------Parent Relationships
				public virtual Document_Type Document_Type {get; set;}
				public virtual ExtendedCustomsProcedures ExtendedCustomsProcedures {get; set;}
				public virtual NationalCustomsProcedures NationalCustomsProcedures {get; set;}
	

	}
}
