// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Common.DataEntites;
using GenSoft.Entities;
using GenSoft.Interfaces;

namespace GenSoft.Entities
{
	public partial class EntityTypeViewModelAttributeValueProperty: BaseEntity, IEntityTypeViewModelAttributeValueProperty
	{
		public virtual int EntityTypeViewModelAttributeId { get; set; }
		public virtual bool IsWriteView { get; set; }
		public virtual string PropertyName { get; set; }
		public virtual string Value { get; set; }

		//-------------------Navigation Properties -------------------------------//
			// ---------Child Relationships
		
			// ---------Parent Relationships
				public virtual EntityTypeViewModelAttributes EntityTypeViewModelAttributes {get; set;}
	

	}
}
