// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Common.DataEntites;
using GenSoft.Entities;
using GenSoft.Interfaces;

namespace GenSoft.Entities
{
	public partial class EntityAttributeChange: BaseEntity, IEntityAttributeChange
	{
		public virtual int PredecessorId { get; set; }
		public virtual int SuccessorId { get; set; }

		//-------------------Navigation Properties -------------------------------//
			// ---------Child Relationships
		
			// ---------Parent Relationships
				public virtual EntityAttribute Predecessors {get; set;}
				public virtual EntityAttribute Successors {get; set;}
	

	}
}
