// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Common.DataEntites;
using GenSoft.Entities;
using GenSoft.Interfaces;

namespace GenSoft.Entities
{
	public partial class EntityViewModelSets: BaseEntity, IEntityViewModelSets
	{
		public virtual int ChildViewModelId { get; set; }
		public virtual int ParentViewModelId { get; set; }

		//-------------------Navigation Properties -------------------------------//
			// ---------Child Relationships
		
			// ---------Parent Relationships
				public virtual EntityTypeViewModel ChildViewModel {get; set;}
				public virtual EntityTypeViewModel ParentViewModel {get; set;}
	

	}
}
