// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Common.DataEntites;
using GenSoft.Entities;
using GenSoft.Interfaces;

namespace GenSoft.Entities
{
	public partial class EntityAttribute: BaseEntity, IEntityAttribute
	{
		public virtual int AttributeId { get; set; }
		public virtual int EntityId { get; set; }
		public virtual string Value { get; set; }

		//-------------------Navigation Properties -------------------------------//
			// ---------Child Relationships
				public virtual ICollection<EntityAttributeChange> Predecessors {get; set;}
				public virtual ICollection<EntityAttributeChange> Successors {get; set;}
		
			// ---------Parent Relationships
				public virtual Attributes Attributes {get; set;}
				public virtual Entity Entity {get; set;}
	

	}
}
