// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Common.DataEntites;
using GenSoft.Entities;
using GenSoft.Interfaces;

namespace GenSoft.Entities
{
	public partial class ExpectedEventPredicateParameter: BaseEntity, IExpectedEventPredicateParameter
	{
		public virtual int EventPredicateId { get; set; }
		public virtual int ExpectedEventId { get; set; }
		public virtual int PredicateParameterId { get; set; }

		//-------------------Navigation Properties -------------------------------//
			// ---------Child Relationships
				public virtual ExpectedEventConstant ExpectedEventConstant {get; set;}
		
			// ---------Parent Relationships
				public virtual EventPredicate EventPredicate {get; set;}
				public virtual ExpectedEvent ExpectedEvent {get; set;}
				public virtual PredicateParameter PredicateParameter {get; set;}
	

	}
}
