// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Common.DataEntites;
using GenSoft.Entities;
using GenSoft.Interfaces;

namespace GenSoft.Entities
{
	public partial class PredicateParameters: BaseEntity, IPredicateParameters
	{
		public virtual int DataTypeId { get; set; }
		public virtual int PredicateId { get; set; }
		public virtual string Name { get; set; }
		public virtual string Description { get; set; }

		//-------------------Navigation Properties -------------------------------//
			// ---------Child Relationships
				public virtual ICollection<ExpectedEventPredicateParameters> ExpectedEventPredicateParameters {get; set;}
		
			// ---------Parent Relationships
				public virtual DataType DataType {get; set;}
				public virtual Predicates Predicates {get; set;}
	

	}
}
