// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Common.DataEntites;
using GenSoft.Entities;
using GenSoft.Interfaces;

namespace GenSoft.Entities
{
	public partial class ProcessState: BaseEntity, IProcessState
	{
		public virtual int ProcessId { get; set; }
		public virtual string Name { get; set; }
		public virtual int StateId { get; set; }

		//-------------------Navigation Properties -------------------------------//
			// ---------Child Relationships
				public virtual SystemProcessStateInfo SystemProcessStateInfo {get; set;}
		
			// ---------Parent Relationships
				public virtual DomainProcess DomainProcess {get; set;}
				public virtual State State {get; set;}
	

	}
}
