// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Common.DataEntites;
using GenSoft.Entities;
using GenSoft.Interfaces;

namespace GenSoft.Entities
{
	public partial class ProcessState: BaseEntity, IProcessState
	{
		public virtual string Name { get; set; }
		public virtual int ProcessId { get; set; }
		public virtual int StateId { get; set; }

		//-------------------Navigation Properties -------------------------------//
			// ---------Child Relationships
				public virtual ICollection<Event> Event {get; set;}
				public virtual ProcessComplexState ProcessComplexState {get; set;}
				public virtual ICollection<ProcessComplexStateExpectedProcessState> ProcessComplexStateExpectedProcessState {get; set;}
				public virtual ICollection<ProcessStateDomainEntityTypes> ProcessStateDomainEntityTypes {get; set;}
				public virtual ProcessStateInfo ProcessStateInfo {get; set;}
				public virtual ICollection<StateAction> StateAction {get; set;}
				public virtual ICollection<StateActionExpectedProcessState> StateActionExpectedProcessState {get; set;}
		
			// ---------Parent Relationships
				public virtual Process Process {get; set;}
				public virtual State State {get; set;}
	

	}
}
