// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Common.DataEntites;
using GenSoft.Entities;
using GenSoft.Interfaces;

namespace GenSoft.Entities
{
	public partial class StateAction: BaseEntity, IStateAction
	{
		public virtual int ActionId { get; set; }
		public virtual int ProcessStateId { get; set; }

		//-------------------Navigation Properties -------------------------------//
			// ---------Child Relationships
				public virtual ICollection<Command> Command {get; set;}
				public virtual StateActionExpectedProcessState StateActionExpectedProcessState {get; set;}
		
			// ---------Parent Relationships
				public virtual Action Action {get; set;}
				public virtual ProcessState ProcessState {get; set;}
	

	}
}
