// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Common.DataEntites;
using GenSoft.Entities;
using GenSoft.Interfaces;

namespace GenSoft.Entities
{
	public partial class StateInfo: BaseEntity, IStateInfo
	{
		public virtual string Name { get; set; }
		public virtual string Status { get; set; }
		public virtual string Subject { get; set; }

		//-------------------Navigation Properties -------------------------------//
			// ---------Child Relationships
				public virtual StateCommandInfo StateCommandInfo {get; set;}
				public virtual StateEventInfo StateEventInfo {get; set;}
				public virtual StateInfoNotes StateInfoNotes {get; set;}
		
			// ---------Parent Relationships
	

	}
}
