// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using Common.DataEntites;
using GenSoft.Interfaces;

namespace GenSoft.Entities
{
	public partial class SystemProcessStateInfo: BaseEntity, ISystemProcessStateInfo
	{
		public virtual string Description { get; set; }
		public virtual string Notes { get; set; }

		//-------------------Navigation Properties -------------------------------//
			// ---------Child Relationships
		
			// ---------Parent Relationships
				public virtual SystemProcessState SystemProcessState {get; set;}
	

	}
}
