// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Common.DataEntites;
using GenSoft.Entities;
using GenSoft.Interfaces;

namespace GenSoft.Entities
{
	public partial class TraceTbl: BaseEntity, ITraceTbl
	{
		public virtual string ApplicationName { get; set; }
		public virtual int ClientProcessID { get; set; }
		public virtual int CPU { get; set; }
		public virtual Int64 Duration { get; set; }
		public virtual DateTime EndTime { get; set; }
		public virtual int EventClass { get; set; }
		public virtual string LoginName { get; set; }
		public virtual string NTUserName { get; set; }
		public virtual Int64 Reads { get; set; }
		public virtual int SPID { get; set; }
		public virtual DateTime StartTime { get; set; }
		public virtual Int64 Writes { get; set; }

		//-------------------Navigation Properties -------------------------------//
			// ---------Child Relationships
		
			// ---------Parent Relationships
	

	}
}
