// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using Common.DataEntites;
using GenSoft.Interfaces;

namespace GenSoft.Entities
{
	public partial class TypeArguement: BaseEntity, ITypeArguement
	{
		public virtual int ChildTypeId { get; set; }
		public virtual int ParentTypeId { get; set; }
		public virtual int TypeId { get; set; }

		//-------------------Navigation Properties -------------------------------//
			// ---------Child Relationships
		
			// ---------Parent Relationships
				public virtual Type ChildTypes {get; set;}
				public virtual Type ParentTypes {get; set;}
				public virtual Type Types {get; set;}
	

	}
}
