// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Common.DataEntites;
using GenSoft.Entities;
using GenSoft.Interfaces;

namespace GenSoft.Entities
{
	public partial class ViewProperty: BaseEntity, IViewProperty
	{
		public virtual string Name { get; set; }

		//-------------------Navigation Properties -------------------------------//
			// ---------Child Relationships
				public virtual ICollection<EntityTypeViewModelAttributeGridProperty> EntityTypeViewModelAttributeGridProperty {get; set;}
				public virtual ICollection<EntityTypeViewModelAttributeLabelProperty> EntityTypeViewModelAttributeLabelProperty {get; set;}
				public virtual ICollection<EntityTypeViewModelAttributeValueProperty> EntityTypeViewModelAttributeValueProperty {get; set;}
		
			// ---------Parent Relationships
	

	}
}
