// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Common.DataEntites;
using GenSoft.Entities;
using GenSoft.Interfaces;

namespace GenSoft.Entities
{
	public partial class xcuda_Export: BaseEntity, Ixcuda_Export
	{
		public virtual int Country_Id { get; set; }
		public virtual string Export_country_code { get; set; }
		public virtual string Export_country_name { get; set; }
		public virtual string Export_country_region { get; set; }

		//-------------------Navigation Properties -------------------------------//
			// ---------Child Relationships
		
			// ---------Parent Relationships
				public virtual xcuda_Country xcuda_Country {get; set;}
	

	}
}
