// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Common.DataEntites;
using GenSoft.Entities;
using GenSoft.Interfaces;

namespace GenSoft.Entities
{
	public partial class xcuda_ASYCUDA_ExtendedProperties: BaseEntity, Ixcuda_ASYCUDA_ExtendedProperties
	{
		public virtual int AsycudaDocumentSetId { get; set; }
		public virtual int ASYCUDA_Id { get; set; }
		public virtual int Customs_ProcedureId { get; set; }
		public virtual string Description { get; set; }
		public virtual int Document_TypeId { get; set; }
		public virtual int DocumentLines { get; set; }
		public virtual bool ImportComplete { get; set; }
		public virtual string ReferenceNumber { get; set; }

		//-------------------Navigation Properties -------------------------------//
			// ---------Child Relationships
				public virtual DocumentManifesto DocumentManifesto {get; set;}
				public virtual DocumentProperties DocumentProperties {get; set;}
		
			// ---------Parent Relationships
				public virtual AsycudaDocumentSet AsycudaDocumentSet {get; set;}
				public virtual xcuda_ASYCUDA xcuda_ASYCUDA {get; set;}
				public virtual Customs_Procedure Customs_Procedure {get; set;}
				public virtual Document_Type Document_Type {get; set;}
	

	}
}
