// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Common.DataEntites;
using GenSoft.Entities;
using GenSoft.Interfaces;

namespace GenSoft.Entities
{
	public partial class xcuda_Packages: BaseEntity, Ixcuda_Packages
	{
		public virtual int Item_Id { get; set; }
		public virtual string Kind_of_packages_code { get; set; }
		public virtual string Kind_of_packages_name { get; set; }
		public virtual string Marks1_of_packages { get; set; }
		public virtual string Marks2_of_packages { get; set; }
		public virtual double Number_of_packages { get; set; }

		//-------------------Navigation Properties -------------------------------//
			// ---------Child Relationships
		
			// ---------Parent Relationships
				public virtual xcuda_Item xcuda_Item {get; set;}
	

	}
}
