// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Common.DataEntites;
using GenSoft.Entities;
using GenSoft.Interfaces;

namespace GenSoft.Entities
{
	public partial class xcuda_receipt: BaseEntity, Ixcuda_receipt
	{
		public virtual int ASYCUDA_Id { get; set; }
		public virtual string Date { get; set; }
		public virtual string Number { get; set; }

		//-------------------Navigation Properties -------------------------------//
			// ---------Child Relationships
		
			// ---------Parent Relationships
				public virtual xcuda_Identification xcuda_Identification {get; set;}
	

	}
}
