// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Common.DataEntites;
using GenSoft.Entities;
using GenSoft.Interfaces;

namespace GenSoft.Entities
{
	public partial class xcuda_Supplementary_unit: BaseEntity, Ixcuda_Supplementary_unit
	{
		public virtual bool IsFirstRow { get; set; }
		public virtual string Suppplementary_unit_code { get; set; }
		public virtual string Suppplementary_unit_name { get; set; }
		public virtual double Suppplementary_unit_quantity { get; set; }
		public virtual int Tarification_Id { get; set; }

		//-------------------Navigation Properties -------------------------------//
			// ---------Child Relationships
		
			// ---------Parent Relationships
				public virtual xcuda_Tarification xcuda_Tarification {get; set;}
	

	}
}
