// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Common.DataEntites;
using GenSoft.Entities;
using GenSoft.Interfaces;

namespace GenSoft.Entities
{
	public partial class xcuda_Transport: BaseEntity, Ixcuda_Transport
	{
		public virtual int ASYCUDA_Id { get; set; }
		public virtual bool Container_flag { get; set; }
		public virtual string Location_of_goods { get; set; }
		public virtual bool Single_waybill_flag { get; set; }

		//-------------------Navigation Properties -------------------------------//
			// ---------Child Relationships
				public virtual ICollection<xcuda_Border_office> xcuda_Border_office {get; set;}
				public virtual ICollection<xcuda_Delivery_terms> xcuda_Delivery_terms {get; set;}
				public virtual ICollection<xcuda_Means_of_transport> xcuda_Means_of_transport {get; set;}
				public virtual ICollection<xcuda_Place_of_loading> xcuda_Place_of_loading {get; set;}
		
			// ---------Parent Relationships
				public virtual xcuda_ASYCUDA xcuda_ASYCUDA {get; set;}
	

	}
}
