// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Common.DataEntites;
using GenSoft.Entities;
using GenSoft.Interfaces;

namespace GenSoft.Entities
{
	public partial class xcuda_HScode: BaseEntity, Ixcuda_HScode
	{
		public virtual string Commodity_code { get; set; }
		public virtual int Item_Id { get; set; }
		public virtual string Precision_1 { get; set; }
		public virtual string Precision_4 { get; set; }

		//-------------------Navigation Properties -------------------------------//
			// ---------Child Relationships
				public virtual xcuda_Inventory_Item xcuda_Inventory_Item {get; set;}
		
			// ---------Parent Relationships
				public virtual xcuda_Tarification xcuda_Tarification {get; set;}
	

	}
}
