// <autogenerated>
//   This file was generated by T4 code generator MRManger-DBContext.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Data;
using GenSoft.Entities;
using System.ComponentModel;
using Microsoft.EntityFrameworkCore;

namespace GenSoft.DBContexts
{
	public partial class GenSoftDBContext
	{
		private static readonly GenSoftDBContext _instance = new GenSoftDBContext();

		public static GenSoftDBContext Instance => _instance;

		static GenSoftDBContext()
		{
			if (System.ComponentModel.LicenseManager.UsageMode == LicenseUsageMode.Designtime) return;
			Instance.Database.EnsureDeleted();
			Instance.Database.EnsureCreated();
			CreateSeedData();
		}

		private static void CreateSeedData()
		{
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[Action] ON
						Insert Into dbo.[Action] (Id,Name) Values('1','StartProcess')
						Insert Into dbo.[Action] (Id,Name) Values('2','StartNextProcess')
						Insert Into dbo.[Action] (Id,Name) Values('3','CleanUpProcess')
					SET IDENTITY_INSERT dbo.[Action] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[Agent] ON
						Insert Into dbo.[Agent] (Id,UserName) Values('0','System')
						Insert Into dbo.[Agent] (Id,UserName) Values('2','joe')
					SET IDENTITY_INSERT dbo.[Agent] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[CommandTypes] ON
						Insert Into dbo.[CommandTypes] (Id,Name) Values('1','IGetEntityWithChanges')
						Insert Into dbo.[CommandTypes] (Id,Name) Values('2','IUpdateEntityWithChanges')
					SET IDENTITY_INSERT dbo.[CommandTypes] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[FunctionSets] ON
						Insert Into dbo.[FunctionSets] (Id,Name) Values('1','Age')
						Insert Into dbo.[FunctionSets] (Id,Name) Values('2','Name')
					SET IDENTITY_INSERT dbo.[FunctionSets] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[Machine] ON
						Insert Into dbo.[Machine] (Id,MachineName,Processors) Values('1','ALPHAQUEST-PC','8')
					SET IDENTITY_INSERT dbo.[Machine] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[ProcessStateTrigger] ON
						Insert Into dbo.[ProcessStateTrigger] (Id,Name) Values('1','All')
						Insert Into dbo.[ProcessStateTrigger] (Id,Name) Values('2','Any')
					SET IDENTITY_INSERT dbo.[ProcessStateTrigger] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[State] ON
						Insert Into dbo.[State] (Id,Name) Values('1','Started')
						Insert Into dbo.[State] (Id,Name) Values('2','Loaded')
						Insert Into dbo.[State] (Id,Name) Values('3','Completed')
					SET IDENTITY_INSERT dbo.[State] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[Type] ON
						Insert Into dbo.[Type] (Id,Name) Values('1','IService')
						Insert Into dbo.[Type] (Id,Name) Values('2','Process')
						Insert Into dbo.[Type] (Id,Name) Values('3','ScreenModel')
						Insert Into dbo.[Type] (Id,Name) Values('4','Patient')
						Insert Into dbo.[Type] (Id,Name) Values('5','int32')
						Insert Into dbo.[Type] (Id,Name) Values('6','string')
						Insert Into dbo.[Type] (Id,Name) Values('7','DateTime')
						Insert Into dbo.[Type] (Id,Name) Values('8','Patient Details')
						Insert Into dbo.[Type] (Id,Name) Values('9','Patient Address')
						Insert Into dbo.[Type] (Id,Name) Values('10','Patient Phone Number')
						Insert Into dbo.[Type] (Id,Name) Values('11','Next of Kin')
						Insert Into dbo.[Type] (Id,Name) Values('12','Non Resident')
						Insert Into dbo.[Type] (Id,Name) Values('13','Vitals')
						Insert Into dbo.[Type] (Id,Name) Values('37','IPatient')
						Insert Into dbo.[Type] (Id,Name) Values('38','SignInInfo')
						Insert Into dbo.[Type] (Id,Name) Values('40','ISignIn')
						Insert Into dbo.[Type] (Id,Name) Values('43','IAddress')
						Insert Into dbo.[Type] (Id,Name) Values('44','IPhoneNumber')
						Insert Into dbo.[Type] (Id,Name) Values('45','Foreign PhoneNumber')
						Insert Into dbo.[Type] (Id,Name) Values('46','Foreign Address')
						Insert Into dbo.[Type] (Id,Name) Values('47','IPerson')
						Insert Into dbo.[Type] (Id,Name) Values('48','IForeignAddress')
						Insert Into dbo.[Type] (Id,Name) Values('49','IForeignPhoneNumber')
						Insert Into dbo.[Type] (Id,Name) Values('50','Func`2')
						Insert Into dbo.[Type] (Id,Name) Values('51','List`1')
						Insert Into dbo.[Type] (Id,Name) Values('52','Object')
						Insert Into dbo.[Type] (Id,Name) Values('53','List<Object>')
						Insert Into dbo.[Type] (Id,Name) Values('54','Func<List<Object>, int>')
						Insert Into dbo.[Type] (Id,Name) Values('55','Array')
						Insert Into dbo.[Type] (Id,Name) Values('56','string[]')
						Insert Into dbo.[Type] (Id,Name) Values('57','IDynamicEntity')
					SET IDENTITY_INSERT dbo.[Type] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[ViewProperty] ON
						Insert Into dbo.[ViewProperty] (Id,Name) Values('1','Visibility')
						Insert Into dbo.[ViewProperty] (Id,Name) Values('2','FontSize')
						Insert Into dbo.[ViewProperty] (Id,Name) Values('3','FontWeight')
					SET IDENTITY_INSERT dbo.[ViewProperty] OFF");
				Instance.Database.ExecuteSqlCommand(@"
						Insert Into dbo.[EntityType] (Id,EntitySetName) Values('4','Patients')
						Insert Into dbo.[EntityType] (Id,EntitySetName) Values('8','Patient Details')
						Insert Into dbo.[EntityType] (Id,EntitySetName) Values('9','Addresses')
						Insert Into dbo.[EntityType] (Id,EntitySetName) Values('10','Phone Numbers')
						Insert Into dbo.[EntityType] (Id,EntitySetName) Values('11','Next of Kins')
						Insert Into dbo.[EntityType] (Id,EntitySetName) Values('12','Non Resident')
						Insert Into dbo.[EntityType] (Id,EntitySetName) Values('13','Vitals')
						Insert Into dbo.[EntityType] (Id,EntitySetName) Values('37','shit')
						Insert Into dbo.[EntityType] (Id,EntitySetName) Values('38','shit')
						Insert Into dbo.[EntityType] (Id,EntitySetName) Values('40','shit')
						Insert Into dbo.[EntityType] (Id,EntitySetName) Values('43','Addresses')
						Insert Into dbo.[EntityType] (Id,EntitySetName) Values('44','PhoneNumbers')
						Insert Into dbo.[EntityType] (Id,EntitySetName) Values('45','Foreign PhoneNumbers')
						Insert Into dbo.[EntityType] (Id,EntitySetName) Values('46','Foreign Addresses')
						Insert Into dbo.[EntityType] (Id,EntitySetName) Values('47','Persons')
						Insert Into dbo.[EntityType] (Id,EntitySetName) Values('48','IForeignAddresses')
						Insert Into dbo.[EntityType] (Id,EntitySetName) Values('49','IForeignPhoneNumbers')
");
			//No test data for ActionEntityType
			//No test data for ActionEntityType
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[Process] ON
						Insert Into dbo.[Process] (UserId,Id,Description,Name,ParentProcessId,Symbol) Values('0','1','Prepare system for Intial Use','Starting System','0','Start')
						Insert Into dbo.[Process] (UserId,Id,Description,Name,ParentProcessId,Symbol) Values('0','2','User Login','User SignOn','1','User')
						Insert Into dbo.[Process] (UserId,Id,Description,Name,ParentProcessId,Symbol) Values('0','3','User Screen','Load User Screen','2','UserScreen')
					SET IDENTITY_INSERT dbo.[Process] OFF");
				Instance.Database.ExecuteSqlCommand(@"
						Insert Into dbo.[SourceType] (Id) Values('1')
");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[MessageSource] ON
						Insert Into dbo.[MessageSource] (MachineId,Id,SourceGuid,Name,SourceTypeId,ProcessId) Values('1','1','575C9BC4-F78F-49F7-AD10-C1F47277A23B','ServiceManager','1','1')
					SET IDENTITY_INSERT dbo.[MessageSource] OFF");
			//No test data for Message
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[Entity] ON
						Insert Into dbo.[Entity] (Id,EntityTypeId,EntryDateTimeStamp) Values('3','37',cast((select Value from AmoebaDB.dbo.TestValues where Id = 195132) as varbinary(max)))
						Insert Into dbo.[Entity] (Id,EntityTypeId,EntryDateTimeStamp) Values('4','40',cast((select Value from AmoebaDB.dbo.TestValues where Id = 195135) as varbinary(max)))
					SET IDENTITY_INSERT dbo.[Entity] OFF");
			//No test data for Message
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[ProcessState] ON
						Insert Into dbo.[ProcessState] (Id,Name,ProcessId,StateId) Values('1','ServiceManagerStarted','1','1')
						Insert Into dbo.[ProcessState] (Id,Name,ProcessId,StateId) Values('2','Process0Started','1','1')
						Insert Into dbo.[ProcessState] (Id,Name,ProcessId,StateId) Values('3','ScreenViewCreated','1','1')
						Insert Into dbo.[ProcessState] (Id,Name,ProcessId,StateId) Values('4','ScreenViewLoaded','1','2')
						Insert Into dbo.[ProcessState] (Id,Name,ProcessId,StateId) Values('5','Process0Completed','1','3')
						Insert Into dbo.[ProcessState] (Id,Name,ProcessId,StateId) Values('6','Process3Started','3','1')
						Insert Into dbo.[ProcessState] (Id,Name,ProcessId,StateId) Values('7','Signin','2','1')
					SET IDENTITY_INSERT dbo.[ProcessState] OFF");
			//No test data for Message
				Instance.Database.ExecuteSqlCommand(@"
						Insert Into dbo.[ProcessComplexState] (Id,StateTriggerId) Values('1','1')
						Insert Into dbo.[ProcessComplexState] (Id,StateTriggerId) Values('5','1')
");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[ProcessComplexStateExpectedProcessState] ON
						Insert Into dbo.[ProcessComplexStateExpectedProcessState] (ComplexStateId,Id,ProcessStateId) Values('1','1','1')
						Insert Into dbo.[ProcessComplexStateExpectedProcessState] (ComplexStateId,Id,ProcessStateId) Values('5','7','2')
						Insert Into dbo.[ProcessComplexStateExpectedProcessState] (ComplexStateId,Id,ProcessStateId) Values('5','2','3')
						Insert Into dbo.[ProcessComplexStateExpectedProcessState] (ComplexStateId,Id,ProcessStateId) Values('5','3','4')
					SET IDENTITY_INSERT dbo.[ProcessComplexStateExpectedProcessState] OFF");
				Instance.Database.ExecuteSqlCommand(@"
						Insert Into dbo.[DomainEntityType] (Id) Values('4')
						Insert Into dbo.[DomainEntityType] (Id) Values('8')
						Insert Into dbo.[DomainEntityType] (Id) Values('9')
						Insert Into dbo.[DomainEntityType] (Id) Values('10')
						Insert Into dbo.[DomainEntityType] (Id) Values('11')
						Insert Into dbo.[DomainEntityType] (Id) Values('12')
						Insert Into dbo.[DomainEntityType] (Id) Values('13')
						Insert Into dbo.[DomainEntityType] (Id) Values('37')
						Insert Into dbo.[DomainEntityType] (Id) Values('38')
						Insert Into dbo.[DomainEntityType] (Id) Values('40')
						Insert Into dbo.[DomainEntityType] (Id) Values('43')
						Insert Into dbo.[DomainEntityType] (Id) Values('44')
						Insert Into dbo.[DomainEntityType] (Id) Values('45')
						Insert Into dbo.[DomainEntityType] (Id) Values('46')
						Insert Into dbo.[DomainEntityType] (Id) Values('47')
						Insert Into dbo.[DomainEntityType] (Id) Values('48')
						Insert Into dbo.[DomainEntityType] (Id) Values('49')
");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[ProcessStateDomainEntityTypes] ON
						Insert Into dbo.[ProcessStateDomainEntityTypes] (DomainEntityTypeId,Id,ProcessStateId) Values('4','1','6')
						Insert Into dbo.[ProcessStateDomainEntityTypes] (DomainEntityTypeId,Id,ProcessStateId) Values('8','2','6')
						Insert Into dbo.[ProcessStateDomainEntityTypes] (DomainEntityTypeId,Id,ProcessStateId) Values('9','5','6')
						Insert Into dbo.[ProcessStateDomainEntityTypes] (DomainEntityTypeId,Id,ProcessStateId) Values('10','6','6')
						Insert Into dbo.[ProcessStateDomainEntityTypes] (DomainEntityTypeId,Id,ProcessStateId) Values('11','7','6')
						Insert Into dbo.[ProcessStateDomainEntityTypes] (DomainEntityTypeId,Id,ProcessStateId) Values('12','8','6')
						Insert Into dbo.[ProcessStateDomainEntityTypes] (DomainEntityTypeId,Id,ProcessStateId) Values('13','9','6')
						Insert Into dbo.[ProcessStateDomainEntityTypes] (DomainEntityTypeId,Id,ProcessStateId) Values('38','33','7')
						Insert Into dbo.[ProcessStateDomainEntityTypes] (DomainEntityTypeId,Id,ProcessStateId) Values('46','34','6')
						Insert Into dbo.[ProcessStateDomainEntityTypes] (DomainEntityTypeId,Id,ProcessStateId) Values('45','35','6')
						Insert Into dbo.[ProcessStateDomainEntityTypes] (DomainEntityTypeId,Id,ProcessStateId) Values('40','36','7')
					SET IDENTITY_INSERT dbo.[ProcessStateDomainEntityTypes] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[EntityTypeViewModel] ON
						Insert Into dbo.[EntityTypeViewModel] (Id,ProcessDomainEntityTypeId,Priority,Symbol,Description,PropertyName) Values('1','1','1','?','Patient List','Patients')
						Insert Into dbo.[EntityTypeViewModel] (Id,ProcessDomainEntityTypeId,Priority,Symbol,Description,PropertyName) Values('2','2','3','?','Patient Details','PatientDetails')
						Insert Into dbo.[EntityTypeViewModel] (Id,ProcessDomainEntityTypeId,Priority,Symbol,Description,PropertyName) Values('3','33','1','?','Sign In','SignIn')
						Insert Into dbo.[EntityTypeViewModel] (Id,ProcessDomainEntityTypeId,Priority,Symbol,Description,PropertyName) Values('4','9','2','?','Vitals','Vitals')
						Insert Into dbo.[EntityTypeViewModel] (Id,ProcessDomainEntityTypeId,Priority,Symbol,Description,PropertyName) Values('5','5','1','A','Patient Addresses','PatientAddresses')
						Insert Into dbo.[EntityTypeViewModel] (Id,ProcessDomainEntityTypeId,Priority,Symbol,Description,PropertyName) Values('6','6','2','P','Patient PhoneNumbers','PatientPhoneNumbers')
						Insert Into dbo.[EntityTypeViewModel] (Id,ProcessDomainEntityTypeId,Priority,Symbol,Description,PropertyName) Values('7','7','3','K','Next Of Kin','NextOfKin')
						Insert Into dbo.[EntityTypeViewModel] (Id,ProcessDomainEntityTypeId,Priority,Symbol,Description,PropertyName) Values('8','8','4','NR','Non-Resident Info','NonResident')
						Insert Into dbo.[EntityTypeViewModel] (Id,ProcessDomainEntityTypeId,Priority,Symbol,Description,PropertyName) Values('9','34','1','A','Foreign Addresses','ForeignAddresses')
						Insert Into dbo.[EntityTypeViewModel] (Id,ProcessDomainEntityTypeId,Priority,Symbol,Description,PropertyName) Values('10','35','2','P','Foreign PhoneNumbers','ForeignPhoneNumbers')
					SET IDENTITY_INSERT dbo.[EntityTypeViewModel] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[ViewModelCommands] ON
						Insert Into dbo.[ViewModelCommands] (CommandTypeId,Id,RequireAllFields,ExistingEntities,Name) Values('1','1','1','0','FindAll')
						Insert Into dbo.[ViewModelCommands] (CommandTypeId,Id,RequireAllFields,ExistingEntities,Name) Values('2','2','0','1','UpdatePartial')
						Insert Into dbo.[ViewModelCommands] (CommandTypeId,Id,RequireAllFields,ExistingEntities,Name) Values('2','3','1','0','CreateAll')
						Insert Into dbo.[ViewModelCommands] (CommandTypeId,Id,RequireAllFields,ExistingEntities,Name) Values('2','4','0','0','CreatePartial')
					SET IDENTITY_INSERT dbo.[ViewModelCommands] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[EntityViewModelCommands] ON
						Insert Into dbo.[EntityViewModelCommands] (EntityViewModelId,Id,ViewModelCommandId) Values('3','1','1')
						Insert Into dbo.[EntityViewModelCommands] (EntityViewModelId,Id,ViewModelCommandId) Values('2','2','2')
						Insert Into dbo.[EntityViewModelCommands] (EntityViewModelId,Id,ViewModelCommandId) Values('1','3','3')
						Insert Into dbo.[EntityViewModelCommands] (EntityViewModelId,Id,ViewModelCommandId) Values('1','4','2')
						Insert Into dbo.[EntityViewModelCommands] (EntityViewModelId,Id,ViewModelCommandId) Values('4','5','2')
						Insert Into dbo.[EntityViewModelCommands] (EntityViewModelId,Id,ViewModelCommandId) Values('5','6','2')
						Insert Into dbo.[EntityViewModelCommands] (EntityViewModelId,Id,ViewModelCommandId) Values('5','7','4')
						Insert Into dbo.[EntityViewModelCommands] (EntityViewModelId,Id,ViewModelCommandId) Values('6','8','2')
						Insert Into dbo.[EntityViewModelCommands] (EntityViewModelId,Id,ViewModelCommandId) Values('6','9','4')
						Insert Into dbo.[EntityViewModelCommands] (EntityViewModelId,Id,ViewModelCommandId) Values('7','10','2')
						Insert Into dbo.[EntityViewModelCommands] (EntityViewModelId,Id,ViewModelCommandId) Values('7','11','4')
						Insert Into dbo.[EntityViewModelCommands] (EntityViewModelId,Id,ViewModelCommandId) Values('8','12','2')
						Insert Into dbo.[EntityViewModelCommands] (EntityViewModelId,Id,ViewModelCommandId) Values('8','13','4')
						Insert Into dbo.[EntityViewModelCommands] (EntityViewModelId,Id,ViewModelCommandId) Values('9','14','2')
						Insert Into dbo.[EntityViewModelCommands] (EntityViewModelId,Id,ViewModelCommandId) Values('9','15','4')
						Insert Into dbo.[EntityViewModelCommands] (EntityViewModelId,Id,ViewModelCommandId) Values('10','16','2')
						Insert Into dbo.[EntityViewModelCommands] (EntityViewModelId,Id,ViewModelCommandId) Values('10','17','4')
					SET IDENTITY_INSERT dbo.[EntityViewModelCommands] OFF");
				Instance.Database.ExecuteSqlCommand(@"
						Insert Into dbo.[ProcessStateInfo] (Id,Description,Notes) Values('1','Service Manager Started','Service Manager Started')
						Insert Into dbo.[ProcessStateInfo] (Id,Description,Notes) Values('2','ProcessStarted','Process 0 Started ')
						Insert Into dbo.[ProcessStateInfo] (Id,Description,Notes) Values('3','ScreenView Created','This view contains all views')
");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[StateAction] ON
						Insert Into dbo.[StateAction] (ActionId,Id,ProcessStateId) Values('1','5','1')
						Insert Into dbo.[StateAction] (ActionId,Id,ProcessStateId) Values('3','6','5')
					SET IDENTITY_INSERT dbo.[StateAction] OFF");
			//No test data for Command
			//No test data for Command
				Instance.Database.ExecuteSqlCommand(@"
						Insert Into dbo.[StateActionExpectedProcessState] (ExpectedProcesStateId,Id) Values('2','5')
");
				Instance.Database.ExecuteSqlCommand(@"
						Insert Into dbo.[User] (Id,Password) Values('2','test')
");
				Instance.Database.ExecuteSqlCommand(@"
						Insert Into dbo.[DataType] (Id) Values('5')
						Insert Into dbo.[DataType] (Id) Values('6')
						Insert Into dbo.[DataType] (Id) Values('7')
						Insert Into dbo.[DataType] (Id) Values('50')
						Insert Into dbo.[DataType] (Id) Values('51')
						Insert Into dbo.[DataType] (Id) Values('52')
						Insert Into dbo.[DataType] (Id) Values('53')
						Insert Into dbo.[DataType] (Id) Values('55')
						Insert Into dbo.[DataType] (Id) Values('56')
						Insert Into dbo.[DataType] (Id) Values('57')
");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[Attributes] ON
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('1','Id','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('2','FirstName','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('3','Address','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('4','PhoneNumber','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('6','Sex','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('7','BirthCountry','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('8','Email','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('9','BirthDate','7')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('11','EmailAddress','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('12','Marital Status','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('40','PatientId','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('41','SyntomId','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('43','InterviewId','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('45','PatientVisitId','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('46','MedicalSystemId','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('48','PatientSyntomId','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('49','QuestionId','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('50','LastName','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('51','UserName','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('52','Password','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('53','Temperature','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('63','Pulse','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('64','Respiratory','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('65','BloodPressure','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('66','SaO2','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('67','City','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('68','Country','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('69','Parish','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('70','State','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('71','AddressType','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('72','PhoneType','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('73','Relationship','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('74','Name','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('75','Type','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('76','BoatName','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('77','Marina','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('78','ArrivalDate','7')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('79','DepartureDate','7')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('80','School','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('81','HotelName','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('82','PersonId','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('84','Zip Code','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('85','Street','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('86','Age','5')
					SET IDENTITY_INSERT dbo.[Attributes] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[EntityAttribute] ON
						Insert Into dbo.[EntityAttribute] (AttributeId,Id,EntityId,Value) Values('1','1','3','3')
						Insert Into dbo.[EntityAttribute] (AttributeId,Id,EntityId,Value) Values('2','2','3','Jonali')
						Insert Into dbo.[EntityAttribute] (AttributeId,Id,EntityId,Value) Values('50','3','3','St. Louis')
						Insert Into dbo.[EntityAttribute] (AttributeId,Id,EntityId,Value) Values('3','4','3','Fort Jeudy')
						Insert Into dbo.[EntityAttribute] (AttributeId,Id,EntityId,Value) Values('4','5','3','456-4724')
						Insert Into dbo.[EntityAttribute] (AttributeId,Id,EntityId,Value) Values('9','6','3','3/16/1994')
						Insert Into dbo.[EntityAttribute] (AttributeId,Id,EntityId,Value) Values('6','7','3','Female')
						Insert Into dbo.[EntityAttribute] (AttributeId,Id,EntityId,Value) Values('51','8','4','joe')
						Insert Into dbo.[EntityAttribute] (AttributeId,Id,EntityId,Value) Values('52','9','4','test')
						Insert Into dbo.[EntityAttribute] (AttributeId,Id,EntityId,Value) Values('1','10','4','1')
					SET IDENTITY_INSERT dbo.[EntityAttribute] OFF");
			//No test data for EntityAttributeChanges
			//No test data for EntityAttributeChanges
				Instance.Database.ExecuteSqlCommand(@"
						Insert Into dbo.[EntityId] (Id) Values('1')
						Insert Into dbo.[EntityId] (Id) Values('67')
						Insert Into dbo.[EntityId] (Id) Values('68')
						Insert Into dbo.[EntityId] (Id) Values('69')
						Insert Into dbo.[EntityId] (Id) Values('70')
						Insert Into dbo.[EntityId] (Id) Values('71')
");
				Instance.Database.ExecuteSqlCommand(@"
						Insert Into dbo.[EntityName] (Id) Values('2')
");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[EntityTypeAttributes] ON
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('1','1','37','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('2','2','37','1')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('3','3','37','2')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('4','4','37','3')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('6','6','37','4')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('7','7','37','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('8','8','37','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('9','9','37','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('11','11','37','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('12','12','37','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('1','13','4','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('2','14','4','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('3','15','4','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('4','16','4','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('1','18','8','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('2','19','8','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('3','20','8','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('4','21','8','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('6','23','8','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('7','24','8','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('8','25','8','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('9','26','8','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('51','30','38','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('52','31','38','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('1','32','38','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('1','33','13','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('53','39','13','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('63','40','13','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('64','41','13','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('65','42','13','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('66','43','13','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('1','44','40','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('3','45','9','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('67','46','9','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('68','47','9','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('69','48','9','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('71','50','9','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('4','51','10','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('72','52','10','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('74','54','11','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('73','55','11','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('3','56','11','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('4','57','11','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('8','58','11','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('75','59','12','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('76','60','12','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('77','61','12','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('78','62','12','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('79','63','12','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('80','64','12','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('81','65','12','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('1','67','43','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('1','68','44','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('1','69','45','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('1','70','46','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('1','71','47','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('82','72','9','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('82','73','10','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('82','74','11','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('1','75','12','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('82','76','46','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('82','77','45','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('3','78','46','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('67','79','46','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('68','80','46','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('71','81','46','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('84','82','46','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('85','83','46','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('70','84','46','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('4','85','45','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('72','86','45','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('1','87','48','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('1','88','49','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('50','89','4','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('74','90','4','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('9','91','4','0')
						Insert Into dbo.[EntityTypeAttributes] (AttributeId,Id,EntityTypeId,Priority) Values('86','92','4','0')
					SET IDENTITY_INSERT dbo.[EntityTypeAttributes] OFF");
				Instance.Database.ExecuteSqlCommand(@"
						Insert Into dbo.[CalculatedProperties] (Id,FunctionSetId) Values('92','1')
");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[EntityRelationships] ON
						Insert Into dbo.[EntityRelationships] (Id,ParentEntityId,ChildEntityId) Values('67','13','18')
						Insert Into dbo.[EntityRelationships] (Id,ParentEntityId,ChildEntityId) Values('69','13','33')
						Insert Into dbo.[EntityRelationships] (Id,ParentEntityId,ChildEntityId) Values('70','44','32')
						Insert Into dbo.[EntityRelationships] (Id,ParentEntityId,ChildEntityId) Values('71','18','72')
						Insert Into dbo.[EntityRelationships] (Id,ParentEntityId,ChildEntityId) Values('73','18','74')
						Insert Into dbo.[EntityRelationships] (Id,ParentEntityId,ChildEntityId) Values('77','18','73')
						Insert Into dbo.[EntityRelationships] (Id,ParentEntityId,ChildEntityId) Values('78','18','75')
						Insert Into dbo.[EntityRelationships] (Id,ParentEntityId,ChildEntityId) Values('79','75','76')
						Insert Into dbo.[EntityRelationships] (Id,ParentEntityId,ChildEntityId) Values('80','75','77')
						Insert Into dbo.[EntityRelationships] (Id,ParentEntityId,ChildEntityId) Values('81','1','13')
					SET IDENTITY_INSERT dbo.[EntityRelationships] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[EntityTypeViewModelAttributes] ON
						Insert Into dbo.[EntityTypeViewModelAttributes] (EntityTypeAttributeId,Id,EntityTypeViewModelId) Values('13','1','1')
						Insert Into dbo.[EntityTypeViewModelAttributes] (EntityTypeAttributeId,Id,EntityTypeViewModelId) Values('14','2','1')
						Insert Into dbo.[EntityTypeViewModelAttributes] (EntityTypeAttributeId,Id,EntityTypeViewModelId) Values('15','3','1')
						Insert Into dbo.[EntityTypeViewModelAttributes] (EntityTypeAttributeId,Id,EntityTypeViewModelId) Values('16','4','1')
						Insert Into dbo.[EntityTypeViewModelAttributes] (EntityTypeAttributeId,Id,EntityTypeViewModelId) Values('30','5','3')
					SET IDENTITY_INSERT dbo.[EntityTypeViewModelAttributes] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[EntityTypeViewModelAttributeGridProperty] ON
						Insert Into dbo.[EntityTypeViewModelAttributeGridProperty] (Id,EntityTypeViewModelAttributeId,ViewPropertyId,Value,IsWriteView) Values('1','2','1','Collapsed','0')
						Insert Into dbo.[EntityTypeViewModelAttributeGridProperty] (Id,EntityTypeViewModelAttributeId,ViewPropertyId,Value,IsWriteView) Values('2','1','1','Collapsed','0')
					SET IDENTITY_INSERT dbo.[EntityTypeViewModelAttributeGridProperty] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[EntityTypeViewModelAttributeLabelProperty] ON
						Insert Into dbo.[EntityTypeViewModelAttributeLabelProperty] (Id,EntityTypeViewModelAttributeId,ViewPropertyId,Value,IsWriteView) Values('1','2','1','Hidden','0')
						Insert Into dbo.[EntityTypeViewModelAttributeLabelProperty] (Id,EntityTypeViewModelAttributeId,ViewPropertyId,Value,IsWriteView) Values('2','3','1','Hidden','0')
					SET IDENTITY_INSERT dbo.[EntityTypeViewModelAttributeLabelProperty] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[EntityTypeViewModelAttributeValueProperty] ON
						Insert Into dbo.[EntityTypeViewModelAttributeValueProperty] (EntityTypeViewModelAttributeId,Id,ViewPropertyId,Value,IsWriteView) Values('2','1','2','18','0')
						Insert Into dbo.[EntityTypeViewModelAttributeValueProperty] (EntityTypeViewModelAttributeId,Id,ViewPropertyId,Value,IsWriteView) Values('3','2','2','16','0')
						Insert Into dbo.[EntityTypeViewModelAttributeValueProperty] (EntityTypeViewModelAttributeId,Id,ViewPropertyId,Value,IsWriteView) Values('4','3','2','14','0')
						Insert Into dbo.[EntityTypeViewModelAttributeValueProperty] (EntityTypeViewModelAttributeId,Id,ViewPropertyId,Value,IsWriteView) Values('2','4','3','Bold','0')
					SET IDENTITY_INSERT dbo.[EntityTypeViewModelAttributeValueProperty] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[Functions] ON
						Insert Into dbo.[Functions] (ReturnDataTypeId,Id,Name,Description,Body) Values('5','1','YearsDateDiff','Calculate Number of Years from Current Date','DateTime.Now.Year - x.Date.Year')
						Insert Into dbo.[Functions] (ReturnDataTypeId,Id,Name,Description,Body) Values('6','2','StringJoin','Concat with character','string.Join(c, x)')
						Insert Into dbo.[Functions] (ReturnDataTypeId,Id,Name,Description,Body) Values('7','3','String2Date','Convert String To Date','DateTime.Parse(x)')
						Insert Into dbo.[Functions] (ReturnDataTypeId,Id,Name,Description,Body) Values('6','4','GetDynamicEntityProperty','Get Dynamic Entity Property','IDynamicEntity.Properties[param0]')
					SET IDENTITY_INSERT dbo.[Functions] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[FunctionParameters] ON
						Insert Into dbo.[FunctionParameters] (Id,FunctionId,Name,DataTypeId) Values('1','4','IDynamicEntity','57')
						Insert Into dbo.[FunctionParameters] (Id,FunctionId,Name,DataTypeId) Values('2','2','x','56')
						Insert Into dbo.[FunctionParameters] (Id,FunctionId,Name,DataTypeId) Values('3','2','c','6')
						Insert Into dbo.[FunctionParameters] (Id,FunctionId,Name,DataTypeId) Values('5','1','x','7')
						Insert Into dbo.[FunctionParameters] (Id,FunctionId,Name,DataTypeId) Values('6','3','x','6')
					SET IDENTITY_INSERT dbo.[FunctionParameters] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[CalculatedPropertyParameters] ON
						Insert Into dbo.[CalculatedPropertyParameters] (CalculatedPropertyId,Id,FunctionParameterId) Values('92','1','1')
					SET IDENTITY_INSERT dbo.[CalculatedPropertyParameters] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[CalculatedPropertyParameterEntityTypes] ON
						Insert Into dbo.[CalculatedPropertyParameterEntityTypes] (Id,CalculatedPropertyParameterId,EntityTypeAttributeId) Values('1','1','91')
					SET IDENTITY_INSERT dbo.[CalculatedPropertyParameterEntityTypes] OFF");
			//No test data for FunctionParameterConstants
			//No test data for FunctionParameterConstants
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[FunctionSetFunctions] ON
						Insert Into dbo.[FunctionSetFunctions] (FunctionId,Id,FunctionSetId) Values('2','1','2')
						Insert Into dbo.[FunctionSetFunctions] (FunctionId,Id,FunctionSetId) Values('4','2','1')
						Insert Into dbo.[FunctionSetFunctions] (FunctionId,Id,FunctionSetId) Values('3','3','1')
						Insert Into dbo.[FunctionSetFunctions] (FunctionId,Id,FunctionSetId) Values('1','4','1')
					SET IDENTITY_INSERT dbo.[FunctionSetFunctions] OFF");
			//No test data for MessageType
			//No test data for MessageType
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[TypeArguements] ON
						Insert Into dbo.[TypeArguements] (TypeId,Id,ParentTypeId,ChildTypeId) Values('53','53','51','52')
						Insert Into dbo.[TypeArguements] (TypeId,Id,ParentTypeId,ChildTypeId) Values('56','54','55','6')
					SET IDENTITY_INSERT dbo.[TypeArguements] OFF");
			//No test data for TypeParameter
			//No test data for TypeParameter
			//No test data for ActionEntityType
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[ApplicationSetting] ON
						Insert Into dbo.[ApplicationSetting] (Id,AutoRun) Values('1','1')
					SET IDENTITY_INSERT dbo.[ApplicationSetting] OFF");
			//No test data for Command
			//No test data for CompositeRequest
			//No test data for DomainEntityCache
				Instance.Database.ExecuteSqlCommand(@"
						Insert Into dbo.[DomainEntityTypeSourceEntity] (Id,SourceEntity) Values('4','Patient')
						Insert Into dbo.[DomainEntityTypeSourceEntity] (Id,SourceEntity) Values('8','Patient')
						Insert Into dbo.[DomainEntityTypeSourceEntity] (Id,SourceEntity) Values('12','NonResident')
						Insert Into dbo.[DomainEntityTypeSourceEntity] (Id,SourceEntity) Values('13','Vitals')
");
			//No test data for EntityAttributeChanges
				Instance.Database.ExecuteSqlCommand(@"
						Insert Into dbo.[EntityList] (Id,Initalize) Values('4','1')
						Insert Into dbo.[EntityList] (Id,Initalize) Values('9','1')
						Insert Into dbo.[EntityList] (Id,Initalize) Values('10','1')
						Insert Into dbo.[EntityList] (Id,Initalize) Values('11','1')
						Insert Into dbo.[EntityList] (Id,Initalize) Values('40','1')
						Insert Into dbo.[EntityList] (Id,Initalize) Values('45','1')
						Insert Into dbo.[EntityList] (Id,Initalize) Values('46','1')
");
				Instance.Database.ExecuteSqlCommand(@"
						Insert Into dbo.[EntityView] (Id,BaseEntityTypeId) Values('4','37')
						Insert Into dbo.[EntityView] (Id,BaseEntityTypeId) Values('8','37')
						Insert Into dbo.[EntityView] (Id,BaseEntityTypeId) Values('9','43')
						Insert Into dbo.[EntityView] (Id,BaseEntityTypeId) Values('10','44')
						Insert Into dbo.[EntityView] (Id,BaseEntityTypeId) Values('11','47')
						Insert Into dbo.[EntityView] (Id,BaseEntityTypeId) Values('12','37')
						Insert Into dbo.[EntityView] (Id,BaseEntityTypeId) Values('13','37')
						Insert Into dbo.[EntityView] (Id,BaseEntityTypeId) Values('38','40')
						Insert Into dbo.[EntityView] (Id,BaseEntityTypeId) Values('45','48')
						Insert Into dbo.[EntityView] (Id,BaseEntityTypeId) Values('46','49')
");
			//No test data for Event
			//No test data for FunctionParameterConstants
			//No test data for Message
			//No test data for MessageType
			//No test data for TypeParameter
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[ViewModelTypes] ON
						Insert Into dbo.[ViewModelTypes] (Id,Name,List,DomainEntity) Values('1','ObservableViewModel','0','0')
						Insert Into dbo.[ViewModelTypes] (Id,Name,List,DomainEntity) Values('2','EntityViewModel','0','1')
						Insert Into dbo.[ViewModelTypes] (Id,Name,List,DomainEntity) Values('3','SummaryListViewModel','1','1')
					SET IDENTITY_INSERT dbo.[ViewModelTypes] OFF");
		}
               
			
		
	}
}
