// <autogenerated>
//   This file was generated by T4 code generator MRManger-DBContext.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Data;
using GenSoft.Entities;
using System.ComponentModel;
using Microsoft.EntityFrameworkCore;

namespace GenSoft.DBContexts
{
	public partial class GenSoftDBContext
	{
		private static readonly GenSoftDBContext _instance = new GenSoftDBContext();

		public static GenSoftDBContext Instance => _instance;

		static GenSoftDBContext()
		{
			if (System.ComponentModel.LicenseManager.UsageMode == LicenseUsageMode.Designtime) return;
			Instance.Database.EnsureDeleted();
			Instance.Database.EnsureCreated();
			CreateSeedData();
		}

		private static void CreateSeedData()
		{
			try
			{
		
			//No test data for Action
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[ActionSet] ON
						Insert Into dbo.[ActionSet] (Id,Name) Values('1','StartProcess')
						Insert Into dbo.[ActionSet] (Id,Name) Values('2','StartNextProcess')
						Insert Into dbo.[ActionSet] (Id,Name) Values('3','CleanUpProcess')
					SET IDENTITY_INSERT dbo.[ActionSet] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[Agent] ON
						Insert Into dbo.[Agent] (Id,UserName) Values('0','System')
						Insert Into dbo.[Agent] (Id,UserName) Values('2','joe')
					SET IDENTITY_INSERT dbo.[Agent] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[Application] ON
						Insert Into dbo.[Application] (Id,Name,DBName) Values('1','GenSoft-Creator','GenSoft-Creator')
						Insert Into dbo.[Application] (Id,Name,DBName) Values('2','PayrollDB','GenSoft-PayrollDB')
						Insert Into dbo.[Application] (Id,Name,DBName) Values('3','MRManager','GenSoft-MRManager')
					SET IDENTITY_INSERT dbo.[Application] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[CommandType] ON
						Insert Into dbo.[CommandType] (Id,Name) Values('1','IGetEntityWithChanges')
						Insert Into dbo.[CommandType] (Id,Name) Values('2','IUpdateEntityWithChanges')
						Insert Into dbo.[CommandType] (Id,Name) Values('3','IViewRowStateChanged')
					SET IDENTITY_INSERT dbo.[CommandType] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[FunctionSets] ON
						Insert Into dbo.[FunctionSets] (Id,Name) Values('1','Age')
						Insert Into dbo.[FunctionSets] (Id,Name) Values('2','2 Field Entity Name')
						Insert Into dbo.[FunctionSets] (Id,Name) Values('3','1 Field Entity  Name')
					SET IDENTITY_INSERT dbo.[FunctionSets] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[Ordinality] ON
						Insert Into dbo.[Ordinality] (Id,Name) Values('1','One')
						Insert Into dbo.[Ordinality] (Id,Name) Values('2','Many')
					SET IDENTITY_INSERT dbo.[Ordinality] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[PresentationPropertyType] ON
						Insert Into dbo.[PresentationPropertyType] (Id,Name) Values('1','AttributeGrid')
						Insert Into dbo.[PresentationPropertyType] (Id,Name) Values('2','AttributeLabel')
						Insert Into dbo.[PresentationPropertyType] (Id,Name) Values('3','AttributeValue')
					SET IDENTITY_INSERT dbo.[PresentationPropertyType] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[PresentationTheme] ON
						Insert Into dbo.[PresentationTheme] (Id,Name) Values('1','Blue')
					SET IDENTITY_INSERT dbo.[PresentationTheme] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[State] ON
						Insert Into dbo.[State] (Id,Name) Values('1','Started')
						Insert Into dbo.[State] (Id,Name) Values('2','Loaded')
						Insert Into dbo.[State] (Id,Name) Values('3','Completed')
					SET IDENTITY_INSERT dbo.[State] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[Type] ON
						Insert Into dbo.[Type] (Id,Name) Values('5','int32')
						Insert Into dbo.[Type] (Id,Name) Values('6','string')
						Insert Into dbo.[Type] (Id,Name) Values('7','DateTime')
						Insert Into dbo.[Type] (Id,Name) Values('50','Func`2')
						Insert Into dbo.[Type] (Id,Name) Values('51','List`1')
						Insert Into dbo.[Type] (Id,Name) Values('52','Object')
						Insert Into dbo.[Type] (Id,Name) Values('53','List<Object>')
						Insert Into dbo.[Type] (Id,Name) Values('55','Array')
						Insert Into dbo.[Type] (Id,Name) Values('56','string[]')
						Insert Into dbo.[Type] (Id,Name) Values('57','IDynamicEntity')
						Insert Into dbo.[Type] (Id,Name) Values('58','List<string>')
						Insert Into dbo.[Type] (Id,Name) Values('62','bool')
						Insert Into dbo.[Type] (Id,Name) Values('63','AccountEntries')
						Insert Into dbo.[Type] (Id,Name) Values('64','Accounts')
						Insert Into dbo.[Type] (Id,Name) Values('65','Accounts_EmployeeAccount')
						Insert Into dbo.[Type] (Id,Name) Values('66','Accounts_InstitutionAccount')
						Insert Into dbo.[Type] (Id,Name) Values('67','AccountTypes')
						Insert Into dbo.[Type] (Id,Name) Values('68','BranchCurrentPayrollJob')
						Insert Into dbo.[Type] (Id,Name) Values('69','Branches')
						Insert Into dbo.[Type] (Id,Name) Values('70','ChargeTypes')
						Insert Into dbo.[Type] (Id,Name) Values('71','EmailTemplate')
						Insert Into dbo.[Type] (Id,Name) Values('72','Employees')
						Insert Into dbo.[Type] (Id,Name) Values('73','Employees_User')
						Insert Into dbo.[Type] (Id,Name) Values('74','Institutions')
						Insert Into dbo.[Type] (Id,Name) Values('75','PayrollEmployeeSetup')
						Insert Into dbo.[Type] (Id,Name) Values('76','PayrollItemParentItem')
						Insert Into dbo.[Type] (Id,Name) Values('77','PayrollItems')
						Insert Into dbo.[Type] (Id,Name) Values('78','PayrollItemSetupItem')
						Insert Into dbo.[Type] (Id,Name) Values('79','PayrollJobEmailTemplates')
						Insert Into dbo.[Type] (Id,Name) Values('80','PayrollJobs')
						Insert Into dbo.[Type] (Id,Name) Values('81','PayrollJobTypes')
						Insert Into dbo.[Type] (Id,Name) Values('82','PayrollSetupItems')
					SET IDENTITY_INSERT dbo.[Type] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[ViewModelTypes] ON
						Insert Into dbo.[ViewModelTypes] (Id,Name,List,DomainEntity) Values('1','ObservableViewModel','0','0')
						Insert Into dbo.[ViewModelTypes] (Id,Name,List,DomainEntity) Values('2','EntityViewModel','0','1')
						Insert Into dbo.[ViewModelTypes] (Id,Name,List,DomainEntity) Values('3','SummaryListViewModel','1','1')
						Insert Into dbo.[ViewModelTypes] (Id,Name,List,DomainEntity) Values('4','CachedViewModel','1','1')
					SET IDENTITY_INSERT dbo.[ViewModelTypes] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[ViewProperty] ON
						Insert Into dbo.[ViewProperty] (Id,Name) Values('1','Visibility')
						Insert Into dbo.[ViewProperty] (Id,Name) Values('2','FontSize')
						Insert Into dbo.[ViewProperty] (Id,Name) Values('3','FontWeight')
						Insert Into dbo.[ViewProperty] (Id,Name) Values('4','ControlType')
					SET IDENTITY_INSERT dbo.[ViewProperty] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[ViewType] ON
						Insert Into dbo.[ViewType] (Id,Name) Values('1','Read')
						Insert Into dbo.[ViewType] (Id,Name) Values('2','Write')
					SET IDENTITY_INSERT dbo.[ViewType] OFF");
		
			//No test data for Action
		
			//No test data for Action
		
			//No test data for Action
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[SystemProcess] ON
						Insert Into dbo.[SystemProcess] (UserId,Id,ParentProcessId,Symbol,Name,Description) Values('0','1','0','Start','Starting System','Prepare system for Intial Use')
						Insert Into dbo.[SystemProcess] (UserId,Id,ParentProcessId,Symbol,Name,Description) Values('0','2','1','BP','Branch Payroll','Process Branch Payroll')
					SET IDENTITY_INSERT dbo.[SystemProcess] OFF");
				Instance.Database.ExecuteSqlCommand(@"
						Insert Into dbo.[DomainProcess] (ApplicationId,Id,Priority) Values('2','2','1')
");
				Instance.Database.ExecuteSqlCommand(@"
						Insert Into dbo.[EntityType] (ApplicationId,Id,EntitySetName) Values('2','63','AccountEntries')
						Insert Into dbo.[EntityType] (ApplicationId,Id,EntitySetName) Values('2','64','Accounts')
						Insert Into dbo.[EntityType] (ApplicationId,Id,EntitySetName) Values('2','65','Accounts_EmployeeAccount')
						Insert Into dbo.[EntityType] (ApplicationId,Id,EntitySetName) Values('2','66','Accounts_InstitutionAccount')
						Insert Into dbo.[EntityType] (ApplicationId,Id,EntitySetName) Values('2','67','AccountTypes')
						Insert Into dbo.[EntityType] (ApplicationId,Id,EntitySetName) Values('2','68','BranchCurrentPayrollJob')
						Insert Into dbo.[EntityType] (ApplicationId,Id,EntitySetName) Values('2','69','Branches')
						Insert Into dbo.[EntityType] (ApplicationId,Id,EntitySetName) Values('2','70','ChargeTypes')
						Insert Into dbo.[EntityType] (ApplicationId,Id,EntitySetName) Values('2','71','EmailTemplate')
						Insert Into dbo.[EntityType] (ApplicationId,Id,EntitySetName) Values('2','72','Employees')
						Insert Into dbo.[EntityType] (ApplicationId,Id,EntitySetName) Values('2','73','Employees_User')
						Insert Into dbo.[EntityType] (ApplicationId,Id,EntitySetName) Values('2','74','Institutions')
						Insert Into dbo.[EntityType] (ApplicationId,Id,EntitySetName) Values('2','75','PayrollEmployeeSetup')
						Insert Into dbo.[EntityType] (ApplicationId,Id,EntitySetName) Values('2','76','PayrollItemParentItem')
						Insert Into dbo.[EntityType] (ApplicationId,Id,EntitySetName) Values('2','77','PayrollItems')
						Insert Into dbo.[EntityType] (ApplicationId,Id,EntitySetName) Values('2','78','PayrollItemSetupItem')
						Insert Into dbo.[EntityType] (ApplicationId,Id,EntitySetName) Values('2','79','PayrollJobEmailTemplates')
						Insert Into dbo.[EntityType] (ApplicationId,Id,EntitySetName) Values('2','80','PayrollJobs')
						Insert Into dbo.[EntityType] (ApplicationId,Id,EntitySetName) Values('2','81','PayrollJobTypes')
						Insert Into dbo.[EntityType] (ApplicationId,Id,EntitySetName) Values('2','82','PayrollSetupItems')
");
		
			//No test data for DomainProcessMainEntity
		
			//No test data for DomainProcessMainEntity
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[ProcessStep] ON
						Insert Into dbo.[ProcessStep] (DomainProcessId,Id,Name,Descripton,Notes,Symbol,Entity) Values('2','2','Select Branch','Select Branch','List of Branches','B         ','Branch')
						Insert Into dbo.[ProcessStep] (DomainProcessId,Id,Name,Descripton,Notes,Symbol,Entity) Values('2','3','Filter PayrollJobs','Branch PayrollJobs','List of PayrollJobs Per Branch','P         ','PayrollJob')
					SET IDENTITY_INSERT dbo.[ProcessStep] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[ProcessPath] ON
						Insert Into dbo.[ProcessPath] (Id,ProcessStepId,NextProcessStepId) Values('1','2','3')
					SET IDENTITY_INSERT dbo.[ProcessPath] OFF");
		
			//No test data for ProcessStepEntity
		
			//No test data for ProcessStepEntity
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[SystemProcessState] ON
						Insert Into dbo.[SystemProcessState] (StateId,Id,Name,ProcessId) Values('1','1','ServiceManagerStarted','1')
						Insert Into dbo.[SystemProcessState] (StateId,Id,Name,ProcessId) Values('1','2','Process0Started','1')
						Insert Into dbo.[SystemProcessState] (StateId,Id,Name,ProcessId) Values('1','3','ScreenViewCreated','1')
						Insert Into dbo.[SystemProcessState] (StateId,Id,Name,ProcessId) Values('2','4','ScreenViewLoaded','1')
						Insert Into dbo.[SystemProcessState] (StateId,Id,Name,ProcessId) Values('3','5','Process0Completed','1')
					SET IDENTITY_INSERT dbo.[SystemProcessState] OFF");
				Instance.Database.ExecuteSqlCommand(@"
						Insert Into dbo.[SystemProcessStateInfo] (Id,Description,Notes) Values('1','Service Manager Started','Service Manager Started')
						Insert Into dbo.[SystemProcessStateInfo] (Id,Description,Notes) Values('2','ProcessStarted','Process 0 Started ')
						Insert Into dbo.[SystemProcessStateInfo] (Id,Description,Notes) Values('3','ScreenView Created','This view contains all views')
");
				Instance.Database.ExecuteSqlCommand(@"
						Insert Into dbo.[User] (Id,Password) Values('2','test')
");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[ApplicationSetting] ON
						Insert Into dbo.[ApplicationSetting] (ApplicationId,Id,AutoRun) Values('2','1','1')
					SET IDENTITY_INSERT dbo.[ApplicationSetting] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[ViewModelCommands] ON
						Insert Into dbo.[ViewModelCommands] (CommandTypeId,Id,RequireAllFields,ExistingEntities,Name) Values('1','1','1','0','FindAll')
						Insert Into dbo.[ViewModelCommands] (CommandTypeId,Id,RequireAllFields,ExistingEntities,Name) Values('2','2','0','1','UpdatePartial')
						Insert Into dbo.[ViewModelCommands] (CommandTypeId,Id,RequireAllFields,ExistingEntities,Name) Values('2','3','1','0','CreateAll')
						Insert Into dbo.[ViewModelCommands] (CommandTypeId,Id,RequireAllFields,ExistingEntities,Name) Values('2','4','0','0','CreatePartial')
						Insert Into dbo.[ViewModelCommands] (CommandTypeId,Id,RequireAllFields,ExistingEntities,Name) Values('3','5','0','0','EditEntity')
					SET IDENTITY_INSERT dbo.[ViewModelCommands] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[EntityTypeViewModelCommand] ON
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('63','2814','2')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('63','2815','3')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('64','2816','2')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('64','2817','3')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('65','2818','2')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('65','2819','3')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('66','2820','2')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('66','2821','3')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('67','2822','2')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('67','2823','3')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('68','2824','2')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('68','2825','3')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('69','2826','2')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('69','2827','3')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('70','2828','2')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('70','2829','3')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('71','2830','2')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('71','2831','3')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('72','2832','2')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('72','2833','3')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('73','2834','2')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('73','2835','3')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('74','2836','2')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('74','2837','3')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('75','2838','2')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('75','2839','3')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('76','2840','2')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('76','2841','3')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('77','2842','2')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('77','2843','3')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('78','2844','2')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('78','2845','3')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('79','2846','2')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('79','2847','3')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('80','2848','2')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('80','2849','3')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('81','2850','2')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('81','2851','3')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('82','2852','2')
						Insert Into dbo.[EntityTypeViewModelCommand] (EntityTypeId,Id,ViewModelCommandId) Values('82','2853','3')
					SET IDENTITY_INSERT dbo.[EntityTypeViewModelCommand] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[RelationshipType] ON
						Insert Into dbo.[RelationshipType] (Id,Name,ParentOrdinalityId,ChildOrdinalityId) Values('1','One-One','1','1')
						Insert Into dbo.[RelationshipType] (Id,Name,ParentOrdinalityId,ChildOrdinalityId) Values('2','One-Many','1','2')
						Insert Into dbo.[RelationshipType] (Id,Name,ParentOrdinalityId,ChildOrdinalityId) Values('3','Many-Many','2','2')
						Insert Into dbo.[RelationshipType] (Id,Name,ParentOrdinalityId,ChildOrdinalityId) Values('1002','Many-One','2','1')
					SET IDENTITY_INSERT dbo.[RelationshipType] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[ViewPropertyPresentationPropertyType] ON
						Insert Into dbo.[ViewPropertyPresentationPropertyType] (Id,ViewPropertyId,PresentationPropertyTypeId) Values('1','1','1')
						Insert Into dbo.[ViewPropertyPresentationPropertyType] (Id,ViewPropertyId,PresentationPropertyTypeId) Values('2','1','2')
						Insert Into dbo.[ViewPropertyPresentationPropertyType] (Id,ViewPropertyId,PresentationPropertyTypeId) Values('3','1','3')
						Insert Into dbo.[ViewPropertyPresentationPropertyType] (Id,ViewPropertyId,PresentationPropertyTypeId) Values('5','2','2')
						Insert Into dbo.[ViewPropertyPresentationPropertyType] (Id,ViewPropertyId,PresentationPropertyTypeId) Values('6','2','3')
						Insert Into dbo.[ViewPropertyPresentationPropertyType] (Id,ViewPropertyId,PresentationPropertyTypeId) Values('7','3','2')
						Insert Into dbo.[ViewPropertyPresentationPropertyType] (Id,ViewPropertyId,PresentationPropertyTypeId) Values('8','3','3')
						Insert Into dbo.[ViewPropertyPresentationPropertyType] (Id,ViewPropertyId,PresentationPropertyTypeId) Values('9','4','3')
					SET IDENTITY_INSERT dbo.[ViewPropertyPresentationPropertyType] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[ViewPropertyValueOptions] ON
						Insert Into dbo.[ViewPropertyValueOptions] (Id,ViewPropertyId,Value) Values('1','1','Collapsed')
						Insert Into dbo.[ViewPropertyValueOptions] (Id,ViewPropertyId,Value) Values('2','1','Hidden')
						Insert Into dbo.[ViewPropertyValueOptions] (Id,ViewPropertyId,Value) Values('3','2','16')
						Insert Into dbo.[ViewPropertyValueOptions] (Id,ViewPropertyId,Value) Values('4','2','18')
						Insert Into dbo.[ViewPropertyValueOptions] (Id,ViewPropertyId,Value) Values('5','2','14')
						Insert Into dbo.[ViewPropertyValueOptions] (Id,ViewPropertyId,Value) Values('6','3','Bold')
						Insert Into dbo.[ViewPropertyValueOptions] (Id,ViewPropertyId,Value) Values('7','3','Normal')
						Insert Into dbo.[ViewPropertyValueOptions] (Id,ViewPropertyId,Value) Values('8','1','Visible')
						Insert Into dbo.[ViewPropertyValueOptions] (Id,ViewPropertyId,Value) Values('10','4','TextBox')
						Insert Into dbo.[ViewPropertyValueOptions] (Id,ViewPropertyId,Value) Values('11','4','ComboBox')
						Insert Into dbo.[ViewPropertyValueOptions] (Id,ViewPropertyId,Value) Values('12','4','CheckBox')
						Insert Into dbo.[ViewPropertyValueOptions] (Id,ViewPropertyId,Value) Values('13','4','DatePicker')
						Insert Into dbo.[ViewPropertyValueOptions] (Id,ViewPropertyId,Value) Values('14','4','TextBlock')
						Insert Into dbo.[ViewPropertyValueOptions] (Id,ViewPropertyId,Value) Values('15','4','EntityComboBox')
						Insert Into dbo.[ViewPropertyValueOptions] (Id,ViewPropertyId,Value) Values('16','4','LookUpTextBlock')
					SET IDENTITY_INSERT dbo.[ViewPropertyValueOptions] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[ViewModelPropertyPresentationType] ON
						Insert Into dbo.[ViewModelPropertyPresentationType] (PresentationThemeId,Id,ViewPropertyPresentationPropertyTypeId,ValueOptionId,ViewTypeId,ViewModelTypeId) Values('1','4','8','6','1','3')
					SET IDENTITY_INSERT dbo.[ViewModelPropertyPresentationType] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[ViewPropertyTheme] ON
						Insert Into dbo.[ViewPropertyTheme] (PresentationThemeId,Id,ViewPropertyPresentationPropertyTypeId,ValueOptionId,ViewTypeId) Values('1','1','1','8','1')
						Insert Into dbo.[ViewPropertyTheme] (PresentationThemeId,Id,ViewPropertyPresentationPropertyTypeId,ValueOptionId,ViewTypeId) Values('1','2','2','8','1')
						Insert Into dbo.[ViewPropertyTheme] (PresentationThemeId,Id,ViewPropertyPresentationPropertyTypeId,ValueOptionId,ViewTypeId) Values('1','3','3','8','1')
						Insert Into dbo.[ViewPropertyTheme] (PresentationThemeId,Id,ViewPropertyPresentationPropertyTypeId,ValueOptionId,ViewTypeId) Values('1','4','5','4','1')
						Insert Into dbo.[ViewPropertyTheme] (PresentationThemeId,Id,ViewPropertyPresentationPropertyTypeId,ValueOptionId,ViewTypeId) Values('1','5','6','4','1')
						Insert Into dbo.[ViewPropertyTheme] (PresentationThemeId,Id,ViewPropertyPresentationPropertyTypeId,ValueOptionId,ViewTypeId) Values('1','6','7','7','1')
						Insert Into dbo.[ViewPropertyTheme] (PresentationThemeId,Id,ViewPropertyPresentationPropertyTypeId,ValueOptionId,ViewTypeId) Values('1','7','8','7','1')
						Insert Into dbo.[ViewPropertyTheme] (PresentationThemeId,Id,ViewPropertyPresentationPropertyTypeId,ValueOptionId,ViewTypeId) Values('1','8','9','14','1')
						Insert Into dbo.[ViewPropertyTheme] (PresentationThemeId,Id,ViewPropertyPresentationPropertyTypeId,ValueOptionId,ViewTypeId) Values('1','9','1','8','2')
						Insert Into dbo.[ViewPropertyTheme] (PresentationThemeId,Id,ViewPropertyPresentationPropertyTypeId,ValueOptionId,ViewTypeId) Values('1','10','2','8','2')
						Insert Into dbo.[ViewPropertyTheme] (PresentationThemeId,Id,ViewPropertyPresentationPropertyTypeId,ValueOptionId,ViewTypeId) Values('1','11','3','8','2')
						Insert Into dbo.[ViewPropertyTheme] (PresentationThemeId,Id,ViewPropertyPresentationPropertyTypeId,ValueOptionId,ViewTypeId) Values('1','12','5','4','2')
						Insert Into dbo.[ViewPropertyTheme] (PresentationThemeId,Id,ViewPropertyPresentationPropertyTypeId,ValueOptionId,ViewTypeId) Values('1','13','6','4','2')
						Insert Into dbo.[ViewPropertyTheme] (PresentationThemeId,Id,ViewPropertyPresentationPropertyTypeId,ValueOptionId,ViewTypeId) Values('1','14','7','7','2')
						Insert Into dbo.[ViewPropertyTheme] (PresentationThemeId,Id,ViewPropertyPresentationPropertyTypeId,ValueOptionId,ViewTypeId) Values('1','15','8','7','2')
						Insert Into dbo.[ViewPropertyTheme] (PresentationThemeId,Id,ViewPropertyPresentationPropertyTypeId,ValueOptionId,ViewTypeId) Values('1','16','9','10','2')
					SET IDENTITY_INSERT dbo.[ViewPropertyTheme] OFF");
				Instance.Database.ExecuteSqlCommand(@"
						Insert Into dbo.[DataType] (Id) Values('5')
						Insert Into dbo.[DataType] (Id) Values('6')
						Insert Into dbo.[DataType] (Id) Values('7')
						Insert Into dbo.[DataType] (Id) Values('50')
						Insert Into dbo.[DataType] (Id) Values('51')
						Insert Into dbo.[DataType] (Id) Values('52')
						Insert Into dbo.[DataType] (Id) Values('53')
						Insert Into dbo.[DataType] (Id) Values('55')
						Insert Into dbo.[DataType] (Id) Values('56')
						Insert Into dbo.[DataType] (Id) Values('57')
						Insert Into dbo.[DataType] (Id) Values('58')
						Insert Into dbo.[DataType] (Id) Values('62')
");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[Attributes] ON
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('1','Id','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('2','AccountId','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('3','EntryTime','7')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('4','Memo','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('5','PayrollItemId','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('6','TradeDate','7')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('7','AccountNumber','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('8','AccountTypeId','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('9','InstitutionId','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('10','Name','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('11','EmployeeId','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('12','PayeeInstitutionId','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('13','CurrentPayrollJobId','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('14','Address','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('15','PhoneNumber','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('16','ShortName','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('17','EmailBody','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('18','FromEmailAddress','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('19','Key','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('20','Subject','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('21','ToEmailAddress','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('22','BranchId','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('23','DriversLicence','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('24','DriversLicenceClass','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('25','EmailAddress','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('26','EmploymentStartDate','7')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('27','EntryDateTime','7')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('28','FirstName','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('29','LastName','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('30','MiddleName','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('31','UnionMember','62')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('32','Password','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('33','Username','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('34','Priority','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('35','ChargeTypeId','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('36','CreditAccountId','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('37','DebitAccountId','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('38','EndDate','7')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('39','PayrollJobTypeId','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('40','PayrollSetupItemId','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('41','RateRounding','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('42','StartDate','7')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('43','ParentPayrollItemId','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('44','ApplyToTaxableBenefits','62')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('45','IncomeDeduction','62')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('46','IsTaxableBenefit','62')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('47','PayrollJobId','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('48','Status','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('49','EmailTemplateId','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('50','CheckedBy','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('51','PaymentDate','7')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('52','PreparedBy','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('53','CompanyAccountId','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('54','CompanyLineItemDescription','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('55','DebitCredit','62')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('56','EmployeeAccountType','6')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('57','PayrollItemAccountId','5')
						Insert Into dbo.[Attributes] (Id,Name,DataTypeId) Values('58','RecuranceDays','6')
					SET IDENTITY_INSERT dbo.[Attributes] OFF");
		
			//No test data for Entity
				Instance.Database.ExecuteSqlCommand(@"
						Insert Into dbo.[EntityId] (Id) Values('1')
");
		
			//No test data for EntityName
		
			//No test data for EntityName
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[EntityTypeAttributes] ON
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('1','63','1','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('2','63','2','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('3','63','3','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('4','63','4','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('5','63','5','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('6','63','6','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('7','64','1','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('8','64','7','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('9','64','8','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('10','64','9','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('11','64','10','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('12','65','1','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('13','65','11','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('14','66','1','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('15','66','12','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('16','67','1','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('17','67','10','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('18','68','1','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('19','68','13','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('20','69','1','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('21','69','10','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('22','69','14','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('23','69','15','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('24','69','16','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('25','70','1','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('26','70','10','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('27','71','1','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('28','71','17','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('29','71','18','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('30','71','19','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('31','71','20','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('32','71','21','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('33','72','1','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('34','72','22','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('35','72','23','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('36','72','24','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('37','72','25','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('38','72','26','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('39','72','27','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('40','72','28','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('41','72','29','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('42','72','30','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('43','72','31','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('44','73','1','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('45','73','11','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('46','73','32','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('47','73','33','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('48','74','1','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('49','74','10','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('50','74','16','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('51','74','34','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('52','75','1','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('53','75','11','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('54','75','35','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('55','75','36','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('56','75','37','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('57','75','38','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('58','75','39','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('59','75','40','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('60','75','41','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('61','75','42','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('62','76','1','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('63','76','43','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('64','77','1','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('65','77','10','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('66','77','11','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('67','77','34','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('68','77','36','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('69','77','37','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('70','77','41','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('71','77','44','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('72','77','45','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('73','77','46','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('74','77','47','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('75','77','48','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('76','78','1','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('77','78','40','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('78','79','1','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('79','79','47','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('80','79','49','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('81','80','1','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('82','80','22','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('83','80','38','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('84','80','39','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('85','80','42','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('86','80','48','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('87','80','50','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('88','80','51','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('89','80','52','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('90','81','1','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('91','81','10','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('92','82','1','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('93','82','10','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('94','82','34','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('95','82','41','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('96','82','44','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('97','82','45','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('98','82','46','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('99','82','53','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('100','82','54','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('101','82','55','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('102','82','56','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('103','82','57','0')
						Insert Into dbo.[EntityTypeAttributes] (Id,EntityTypeId,AttributeId,Priority) Values('104','82','58','0')
					SET IDENTITY_INSERT dbo.[EntityTypeAttributes] OFF");
		
			//No test data for ActionProperties
		
			//No test data for ActionProperties
		
			//No test data for ActionProperties
		
			//No test data for BaseEntityTypeAttribute
		
			//No test data for BaseEntityTypeAttribute
		
			//No test data for CalculatedProperties
		
			//No test data for CalculatedProperties
		
			//No test data for CalculatedProperties
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[EntityRelationship] ON
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('1','2','2')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('2','12','1')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('3','14','1')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('4','55','2')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('5','56','2')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('6','68','2')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('7','69','2')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('8','103','2')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('9','9','2')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('10','18','1')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('11','34','2')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('12','82','2')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('13','54','2')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('14','80','2')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('15','13','2')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('16','45','1')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('17','53','2')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('18','66','2')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('19','10','2')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('20','15','2')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('21','5','2')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('22','62','1')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('23','76','1')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('24','19','2')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('25','74','2')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('26','79','2')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('27','58','2')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('28','84','2')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('29','59','2')
						Insert Into dbo.[EntityRelationship] (Id,ChildEntityId,RelationshipTypeId) Values('30','77','2')
					SET IDENTITY_INSERT dbo.[EntityRelationship] OFF");
				Instance.Database.ExecuteSqlCommand(@"
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('1','7')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('2','7')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('3','7')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('4','7')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('5','7')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('6','7')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('7','7')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('8','7')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('9','16')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('10','20')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('11','20')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('12','20')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('13','25')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('14','27')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('15','33')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('16','33')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('17','33')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('18','33')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('19','48')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('20','48')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('21','64')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('22','64')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('23','64')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('24','81')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('25','81')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('26','81')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('27','90')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('28','90')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('29','92')
						Insert Into dbo.[ParentEntity] (Id,ParentEntityId) Values('30','92')
");
		
			//No test data for ProcessStepRelationship
		
			//No test data for ProcessStepRelationship
		
			//No test data for EntityTypeAttributeCache
		
			//No test data for EntityTypeAttributeCache
		
			//No test data for EntityTypePresentationProperty
		
			//No test data for EntityTypePresentationProperty
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[Functions] ON
						Insert Into dbo.[Functions] (ReturnDataTypeId,Id,Name,Description,Body) Values('5','1','YearsDateDiff','Calculate Number of Years from Current Date','DateTime.Now.Year - x.Date.Year')
						Insert Into dbo.[Functions] (ReturnDataTypeId,Id,Name,Description,Body) Values('6','2','StringJoin','Concat with character','string.Join(const0, x)')
						Insert Into dbo.[Functions] (ReturnDataTypeId,Id,Name,Description,Body) Values('7','3','String2Date','Convert String To Date','DateTime.Parse(x)')
						Insert Into dbo.[Functions] (ReturnDataTypeId,Id,Name,Description,Body) Values('6','4','GetDynamicEntityProperty','Get Dynamic Entity Property','IDynamicEntity.Properties[param0]')
						Insert Into dbo.[Functions] (ReturnDataTypeId,Id,Name,Description,Body) Values('56','7','CreateList','Create New List','(IDynamicEntity.Properties[param0].ToString() +"","" + IDynamicEntity.Properties[param1].ToString()).Split('','')')
					SET IDENTITY_INSERT dbo.[Functions] OFF");
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[FunctionParameter] ON
						Insert Into dbo.[FunctionParameter] (Id,FunctionId,Name,DataTypeId) Values('1','4','IDynamicEntity','57')
						Insert Into dbo.[FunctionParameter] (Id,FunctionId,Name,DataTypeId) Values('2','2','x','56')
						Insert Into dbo.[FunctionParameter] (Id,FunctionId,Name,DataTypeId) Values('5','1','x','7')
						Insert Into dbo.[FunctionParameter] (Id,FunctionId,Name,DataTypeId) Values('6','3','x','6')
						Insert Into dbo.[FunctionParameter] (Id,FunctionId,Name,DataTypeId) Values('11','7','IDynamicEntity','57')
					SET IDENTITY_INSERT dbo.[FunctionParameter] OFF");
		
			//No test data for CalculatedProperties
		
			//No test data for CalculatedProperties
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[FunctionSetFunctions] ON
						Insert Into dbo.[FunctionSetFunctions] (FunctionId,Id,FunctionSetId) Values('4','2','1')
						Insert Into dbo.[FunctionSetFunctions] (FunctionId,Id,FunctionSetId) Values('3','3','1')
						Insert Into dbo.[FunctionSetFunctions] (FunctionId,Id,FunctionSetId) Values('1','4','1')
						Insert Into dbo.[FunctionSetFunctions] (FunctionId,Id,FunctionSetId) Values('7','6','2')
						Insert Into dbo.[FunctionSetFunctions] (FunctionId,Id,FunctionSetId) Values('2','8','2')
						Insert Into dbo.[FunctionSetFunctions] (FunctionId,Id,FunctionSetId) Values('4','9','3')
					SET IDENTITY_INSERT dbo.[FunctionSetFunctions] OFF");
		
			//No test data for SourceType
		
			//No test data for SourceType
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[TypeArguement] ON
						Insert Into dbo.[TypeArguement] (TypeId,Id,ParentTypeId,ChildTypeId) Values('53','53','51','52')
						Insert Into dbo.[TypeArguement] (TypeId,Id,ParentTypeId,ChildTypeId) Values('56','54','55','6')
						Insert Into dbo.[TypeArguement] (TypeId,Id,ParentTypeId,ChildTypeId) Values('58','56','51','6')
					SET IDENTITY_INSERT dbo.[TypeArguement] OFF");
		
			//No test data for EntityTypePresentationProperty
		
			//No test data for EntityTypePresentationProperty
		
			//No test data for Action
		
			//No test data for Action
		
			//No test data for ActionParameterConstants
		
			//No test data for ActionParameterEntityTypeAttributes
		
			//No test data for ActionProperties
		
			//No test data for ActionProperties
		
			//No test data for ActionProperties
		
			//No test data for ActionProperties
		
			//No test data for ActionSetActions
		
			//No test data for BaseEntityTypeAttribute
		
			//No test data for CalculatedProperties
		
			//No test data for CalculatedProperties
		
			//No test data for CalculatedPropertyParameterEntityTypes
		
			//No test data for Command
				Instance.Database.ExecuteSqlCommand(@"
						Insert Into dbo.[DBType] (Id,TableName,SchemaName) Values('63','AccountEntries','dbo')
						Insert Into dbo.[DBType] (Id,TableName,SchemaName) Values('64','Accounts','dbo')
						Insert Into dbo.[DBType] (Id,TableName,SchemaName) Values('65','Accounts_EmployeeAccount','dbo')
						Insert Into dbo.[DBType] (Id,TableName,SchemaName) Values('66','Accounts_InstitutionAccount','dbo')
						Insert Into dbo.[DBType] (Id,TableName,SchemaName) Values('67','AccountTypes','dbo')
						Insert Into dbo.[DBType] (Id,TableName,SchemaName) Values('68','BranchCurrentPayrollJob','dbo')
						Insert Into dbo.[DBType] (Id,TableName,SchemaName) Values('69','Branches','dbo')
						Insert Into dbo.[DBType] (Id,TableName,SchemaName) Values('70','ChargeTypes','dbo')
						Insert Into dbo.[DBType] (Id,TableName,SchemaName) Values('71','EmailTemplate','dbo')
						Insert Into dbo.[DBType] (Id,TableName,SchemaName) Values('72','Employees','dbo')
						Insert Into dbo.[DBType] (Id,TableName,SchemaName) Values('73','Employees_User','dbo')
						Insert Into dbo.[DBType] (Id,TableName,SchemaName) Values('74','Institutions','dbo')
						Insert Into dbo.[DBType] (Id,TableName,SchemaName) Values('75','PayrollEmployeeSetup','dbo')
						Insert Into dbo.[DBType] (Id,TableName,SchemaName) Values('76','PayrollItemParentItem','dbo')
						Insert Into dbo.[DBType] (Id,TableName,SchemaName) Values('77','PayrollItems','dbo')
						Insert Into dbo.[DBType] (Id,TableName,SchemaName) Values('78','PayrollItemSetupItem','dbo')
						Insert Into dbo.[DBType] (Id,TableName,SchemaName) Values('79','PayrollJobEmailTemplates','dbo')
						Insert Into dbo.[DBType] (Id,TableName,SchemaName) Values('80','PayrollJobs','dbo')
						Insert Into dbo.[DBType] (Id,TableName,SchemaName) Values('81','PayrollJobTypes','dbo')
						Insert Into dbo.[DBType] (Id,TableName,SchemaName) Values('82','PayrollSetupItems','dbo')
");
		
			//No test data for DomainProcessMainEntity
		
			//No test data for Entity
		
			//No test data for Entity
		
			//No test data for EntityAttributeChange
		
			//No test data for EntityName
		
			//No test data for EntityTypeAttributeCache
		
			//No test data for EntityTypePresentationProperty
		
			//No test data for EntityView
		
			//No test data for FunctionParameterConstant
				Instance.Database.ExecuteSqlCommand(@"
					SET IDENTITY_INSERT dbo.[Machine] ON
						Insert Into dbo.[Machine] (Id,MachineName,Processors) Values('1','ALPHAQUEST-PC','8')
					SET IDENTITY_INSERT dbo.[Machine] OFF");
		
			//No test data for ProcessStepEntity
		
			//No test data for ProcessStepParentEntity
		
			//No test data for ProcessStepRelationship
		
			//No test data for SourceType
			
			}
		    catch (Exception e)
		    {
		        Console.WriteLine(e);
		        throw;
		    }
		}
               
			
		
	}
}
