

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    public sealed partial class DataType : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the DataType entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DataType()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DataType(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.DataType> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.DataType.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DataType_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DataType_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.DataType.DetailsClass.GetValue(this, global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties.Id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.DataType.DetailsClass.GetValue(this, global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.DataType.DetailsClass.SetValue(this, global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.EntityProperty> EntityProperties
        {
            get
            {
                return global::LightSwitchApplication.DataType.DetailsClass.GetValue(this, global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties.EntityProperties);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.EntityProperty> EntityPropertiesQuery
        {
            get
            {
                return global::LightSwitchApplication.DataType.DetailsClass.GetQuery(this, global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties.EntityProperties);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Parameter> Parameters
        {
            get
            {
                return global::LightSwitchApplication.DataType.DetailsClass.GetValue(this, global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties.Parameters);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Parameter> ParametersQuery
        {
            get
            {
                return global::LightSwitchApplication.DataType.DetailsClass.GetQuery(this, global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties.Parameters);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.DataType,
                global::LightSwitchApplication.DataType.DetailsClass,
                global::LightSwitchApplication.DataType.DetailsClass.IImplementation,
                global::LightSwitchApplication.DataType.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass>.Entry
                __DataTypeEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass>.Entry(
                    global::LightSwitchApplication.DataType.DetailsClass.__DataType_CreateNew,
                    global::LightSwitchApplication.DataType.DetailsClass.__DataType_Created,
                    global::LightSwitchApplication.DataType.DetailsClass.__DataType_AllowSaveWithErrors);
            private static global::LightSwitchApplication.DataType __DataType_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.DataType> es)
            {
                return new global::LightSwitchApplication.DataType(es);
            }
            private static void __DataType_Created(global::LightSwitchApplication.DataType e)
            {
                e.DataType_Created();
            }
            private static bool __DataType_AllowSaveWithErrors(global::LightSwitchApplication.DataType e)
            {
                bool result = false;
                e.DataType_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.DataType.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass, global::LightSwitchApplication.EntityProperty> EntityProperties
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties.EntityProperties) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass, global::LightSwitchApplication.EntityProperty>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass, global::LightSwitchApplication.Parameter> Parameters
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties.Parameters) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass, global::LightSwitchApplication.Parameter>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; }
                new string Name { get; set; }
                new global::System.Collections.IEnumerable EntityProperties { get; }
                new global::System.Collections.IEnumerable Parameters { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DataType.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass, int>.Data> c, global::LightSwitchApplication.DataType.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.DataType e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.DataType e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.DataType.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.DataType e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DataType.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass, string>.Data> c, global::LightSwitchApplication.DataType.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.DataType e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.DataType e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.DataType.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.DataType.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.DataType e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass, global::LightSwitchApplication.EntityProperty>.Entry
                    EntityProperties = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass, global::LightSwitchApplication.EntityProperty>.Entry(
                        "EntityProperties",
                        global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties._EntityProperties_Stub,
                        global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties._EntityProperties_GetReferencedEntities,
                        global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties._EntityProperties_GetEntityCollection);
                private static void _EntityProperties_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DataType.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass, global::LightSwitchApplication.EntityProperty>.Data> c, global::LightSwitchApplication.DataType.DetailsClass d, object sf)
                {
                    c(d, ref d._EntityProperties, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.EntityProperty> _EntityProperties_GetReferencedEntities(global::LightSwitchApplication.DataType.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass>(global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties.EntityProperties, ref d._EntityProperties);
                }
                private static global::System.Collections.IEnumerable _EntityProperties_GetEntityCollection(global::LightSwitchApplication.DataType.DetailsClass d)
                {
                    return d.ImplementationEntity.EntityProperties;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass, global::LightSwitchApplication.Parameter>.Entry
                    Parameters = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass, global::LightSwitchApplication.Parameter>.Entry(
                        "Parameters",
                        global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties._Parameters_Stub,
                        global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties._Parameters_GetReferencedEntities,
                        global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties._Parameters_GetEntityCollection);
                private static void _Parameters_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DataType.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass, global::LightSwitchApplication.Parameter>.Data> c, global::LightSwitchApplication.DataType.DetailsClass d, object sf)
                {
                    c(d, ref d._Parameters, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Parameter> _Parameters_GetReferencedEntities(global::LightSwitchApplication.DataType.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Parameter, global::LightSwitchApplication.Parameter.DetailsClass>(global::LightSwitchApplication.DataType.DetailsClass.PropertySetProperties.Parameters, ref d._Parameters);
                }
                private static global::System.Collections.IEnumerable _Parameters_GetEntityCollection(global::LightSwitchApplication.DataType.DetailsClass d)
                {
                    return d.ImplementationEntity.Parameters;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass, global::LightSwitchApplication.EntityProperty>.Data _EntityProperties;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass, global::LightSwitchApplication.Parameter>.Data _Parameters;
            
        }
    
        #endregion
    }
    
    #endregion
}
