

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    public sealed partial class EntityProperty : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the EntityProperty entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public EntityProperty()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public EntityProperty(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.EntityProperty> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.EntityProperty.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EntityProperty_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EntityProperty_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.EntityProperty.DetailsClass.GetValue(this, global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.Id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string PropertyName
        {
            get
            {
                return global::LightSwitchApplication.EntityProperty.DetailsClass.GetValue(this, global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.PropertyName);
            }
            set
            {
                global::LightSwitchApplication.EntityProperty.DetailsClass.SetValue(this, global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.PropertyName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PropertyName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PropertyName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PropertyName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ModelTypeId
        {
            get
            {
                return global::LightSwitchApplication.EntityProperty.DetailsClass.GetValue(this, global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.ModelTypeId);
            }
            set
            {
                global::LightSwitchApplication.EntityProperty.DetailsClass.SetValue(this, global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.ModelTypeId, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModelTypeId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModelTypeId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModelTypeId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.CalculatedProperty CalculatedProperty
        {
            get
            {
                return global::LightSwitchApplication.EntityProperty.DetailsClass.GetValue(this, global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.CalculatedProperty);
            }
            set
            {
                global::LightSwitchApplication.EntityProperty.DetailsClass.SetValue(this, global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.CalculatedProperty, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CalculatedProperty_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CalculatedProperty_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CalculatedProperty_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.EntityParameter> EntityParameters
        {
            get
            {
                return global::LightSwitchApplication.EntityProperty.DetailsClass.GetValue(this, global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.EntityParameters);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.EntityParameter> EntityParametersQuery
        {
            get
            {
                return global::LightSwitchApplication.EntityProperty.DetailsClass.GetQuery(this, global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.EntityParameters);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.DataType DataType
        {
            get
            {
                return global::LightSwitchApplication.EntityProperty.DetailsClass.GetValue(this, global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.DataType);
            }
            set
            {
                global::LightSwitchApplication.EntityProperty.DetailsClass.SetValue(this, global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.DataType, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DataType_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DataType_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DataType_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Entity Entity
        {
            get
            {
                return global::LightSwitchApplication.EntityProperty.DetailsClass.GetValue(this, global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.Entity);
            }
            set
            {
                global::LightSwitchApplication.EntityProperty.DetailsClass.SetValue(this, global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.Entity, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Entity_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Entity_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Entity_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.EntityProperty,
                global::LightSwitchApplication.EntityProperty.DetailsClass,
                global::LightSwitchApplication.EntityProperty.DetailsClass.IImplementation,
                global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass>.Entry
                __EntityPropertyEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass>.Entry(
                    global::LightSwitchApplication.EntityProperty.DetailsClass.__EntityProperty_CreateNew,
                    global::LightSwitchApplication.EntityProperty.DetailsClass.__EntityProperty_Created,
                    global::LightSwitchApplication.EntityProperty.DetailsClass.__EntityProperty_AllowSaveWithErrors);
            private static global::LightSwitchApplication.EntityProperty __EntityProperty_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.EntityProperty> es)
            {
                return new global::LightSwitchApplication.EntityProperty(es);
            }
            private static void __EntityProperty_Created(global::LightSwitchApplication.EntityProperty e)
            {
                e.EntityProperty_Created();
            }
            private static bool __EntityProperty_AllowSaveWithErrors(global::LightSwitchApplication.EntityProperty e)
            {
                bool result = false;
                e.EntityProperty_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, string> PropertyName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.PropertyName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, int> ModelTypeId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.ModelTypeId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, global::LightSwitchApplication.CalculatedProperty> CalculatedProperty
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.CalculatedProperty) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, global::LightSwitchApplication.CalculatedProperty>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, global::LightSwitchApplication.EntityParameter> EntityParameters
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.EntityParameters) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, global::LightSwitchApplication.EntityParameter>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, global::LightSwitchApplication.DataType> DataType
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.DataType) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, global::LightSwitchApplication.DataType>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, global::LightSwitchApplication.Entity> Entity
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.Entity) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, global::LightSwitchApplication.Entity>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; }
                new string PropertyName { get; set; }
                new int ModelTypeId { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation CalculatedProperty { get; set; }
                new global::System.Collections.IEnumerable EntityParameters { get; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation DataType { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Entity { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EntityProperty.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, int>.Data> c, global::LightSwitchApplication.EntityProperty.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.EntityProperty e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.EntityProperty e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.EntityProperty.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.EntityProperty e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, string>.Entry
                    PropertyName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, string>.Entry(
                        "PropertyName",
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._PropertyName_Stub,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._PropertyName_ComputeIsReadOnly,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._PropertyName_Validate,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._PropertyName_GetImplementationValue,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._PropertyName_SetImplementationValue,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._PropertyName_OnValueChanged);
                private static void _PropertyName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EntityProperty.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, string>.Data> c, global::LightSwitchApplication.EntityProperty.DetailsClass d, object sf)
                {
                    c(d, ref d._PropertyName, sf);
                }
                private static bool _PropertyName_ComputeIsReadOnly(global::LightSwitchApplication.EntityProperty e)
                {
                    bool result = false;
                    e.PropertyName_IsReadOnly(ref result);
                    return result;
                }
                private static void _PropertyName_Validate(global::LightSwitchApplication.EntityProperty e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PropertyName_Validate(r);
                }
                private static string _PropertyName_GetImplementationValue(global::LightSwitchApplication.EntityProperty.DetailsClass d)
                {
                    return d.ImplementationEntity.PropertyName;
                }
                private static void _PropertyName_SetImplementationValue(global::LightSwitchApplication.EntityProperty.DetailsClass d, string v)
                {
                    d.ImplementationEntity.PropertyName = v;
                }
                private static void _PropertyName_OnValueChanged(global::LightSwitchApplication.EntityProperty e)
                {
                    e.PropertyName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, int>.Entry
                    ModelTypeId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, int>.Entry(
                        "ModelTypeId",
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._ModelTypeId_Stub,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._ModelTypeId_ComputeIsReadOnly,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._ModelTypeId_Validate,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._ModelTypeId_GetImplementationValue,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._ModelTypeId_SetImplementationValue,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._ModelTypeId_OnValueChanged);
                private static void _ModelTypeId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EntityProperty.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, int>.Data> c, global::LightSwitchApplication.EntityProperty.DetailsClass d, object sf)
                {
                    c(d, ref d._ModelTypeId, sf);
                }
                private static bool _ModelTypeId_ComputeIsReadOnly(global::LightSwitchApplication.EntityProperty e)
                {
                    bool result = false;
                    e.ModelTypeId_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModelTypeId_Validate(global::LightSwitchApplication.EntityProperty e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModelTypeId_Validate(r);
                }
                private static int _ModelTypeId_GetImplementationValue(global::LightSwitchApplication.EntityProperty.DetailsClass d)
                {
                    return d.ImplementationEntity.ModelTypeId;
                }
                private static void _ModelTypeId_SetImplementationValue(global::LightSwitchApplication.EntityProperty.DetailsClass d, int v)
                {
                    d.ImplementationEntity.ModelTypeId = v;
                }
                private static void _ModelTypeId_OnValueChanged(global::LightSwitchApplication.EntityProperty e)
                {
                    e.ModelTypeId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, global::LightSwitchApplication.CalculatedProperty>.Entry
                    CalculatedProperty = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, global::LightSwitchApplication.CalculatedProperty>.Entry(
                        "CalculatedProperty",
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._CalculatedProperty_Stub,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._CalculatedProperty_ComputeIsReadOnly,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._CalculatedProperty_Validate,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._CalculatedProperty_GetCoreImplementationValue,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._CalculatedProperty_GetImplementationValue,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._CalculatedProperty_SetImplementationValue,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._CalculatedProperty_Refresh,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._CalculatedProperty_OnValueChanged);
                private static void _CalculatedProperty_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EntityProperty.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, global::LightSwitchApplication.CalculatedProperty>.Data> c, global::LightSwitchApplication.EntityProperty.DetailsClass d, object sf)
                {
                    c(d, ref d._CalculatedProperty, sf);
                }
                private static bool _CalculatedProperty_ComputeIsReadOnly(global::LightSwitchApplication.EntityProperty e)
                {
                    bool result = false;
                    e.CalculatedProperty_IsReadOnly(ref result);
                    return result;
                }
                private static void _CalculatedProperty_Validate(global::LightSwitchApplication.EntityProperty e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CalculatedProperty_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _CalculatedProperty_GetCoreImplementationValue(global::LightSwitchApplication.EntityProperty.DetailsClass d)
                {
                    return d.ImplementationEntity.CalculatedProperty;
                }
                private static global::LightSwitchApplication.CalculatedProperty _CalculatedProperty_GetImplementationValue(global::LightSwitchApplication.EntityProperty.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.CalculatedProperty, global::LightSwitchApplication.CalculatedProperty.DetailsClass>(global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.CalculatedProperty, ref d._CalculatedProperty);
                }
                private static void _CalculatedProperty_SetImplementationValue(global::LightSwitchApplication.EntityProperty.DetailsClass d, global::LightSwitchApplication.CalculatedProperty v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.CalculatedProperty, ref d._CalculatedProperty, (i, ev) => i.CalculatedProperty = ev, v);
                }
                private static void _CalculatedProperty_Refresh(global::LightSwitchApplication.EntityProperty.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.CalculatedProperty, ref d._CalculatedProperty);
                }
                private static void _CalculatedProperty_OnValueChanged(global::LightSwitchApplication.EntityProperty e)
                {
                    e.CalculatedProperty_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, global::LightSwitchApplication.EntityParameter>.Entry
                    EntityParameters = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, global::LightSwitchApplication.EntityParameter>.Entry(
                        "EntityParameters",
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._EntityParameters_Stub,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._EntityParameters_GetReferencedEntities,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._EntityParameters_GetEntityCollection);
                private static void _EntityParameters_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EntityProperty.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, global::LightSwitchApplication.EntityParameter>.Data> c, global::LightSwitchApplication.EntityProperty.DetailsClass d, object sf)
                {
                    c(d, ref d._EntityParameters, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.EntityParameter> _EntityParameters_GetReferencedEntities(global::LightSwitchApplication.EntityProperty.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.EntityParameter, global::LightSwitchApplication.EntityParameter.DetailsClass>(global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.EntityParameters, ref d._EntityParameters);
                }
                private static global::System.Collections.IEnumerable _EntityParameters_GetEntityCollection(global::LightSwitchApplication.EntityProperty.DetailsClass d)
                {
                    return d.ImplementationEntity.EntityParameters;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, global::LightSwitchApplication.DataType>.Entry
                    DataType = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, global::LightSwitchApplication.DataType>.Entry(
                        "DataType",
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._DataType_Stub,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._DataType_ComputeIsReadOnly,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._DataType_Validate,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._DataType_GetCoreImplementationValue,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._DataType_GetImplementationValue,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._DataType_SetImplementationValue,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._DataType_Refresh,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._DataType_OnValueChanged);
                private static void _DataType_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EntityProperty.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, global::LightSwitchApplication.DataType>.Data> c, global::LightSwitchApplication.EntityProperty.DetailsClass d, object sf)
                {
                    c(d, ref d._DataType, sf);
                }
                private static bool _DataType_ComputeIsReadOnly(global::LightSwitchApplication.EntityProperty e)
                {
                    bool result = false;
                    e.DataType_IsReadOnly(ref result);
                    return result;
                }
                private static void _DataType_Validate(global::LightSwitchApplication.EntityProperty e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DataType_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _DataType_GetCoreImplementationValue(global::LightSwitchApplication.EntityProperty.DetailsClass d)
                {
                    return d.ImplementationEntity.DataType;
                }
                private static global::LightSwitchApplication.DataType _DataType_GetImplementationValue(global::LightSwitchApplication.EntityProperty.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.DataType, global::LightSwitchApplication.DataType.DetailsClass>(global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.DataType, ref d._DataType);
                }
                private static void _DataType_SetImplementationValue(global::LightSwitchApplication.EntityProperty.DetailsClass d, global::LightSwitchApplication.DataType v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.DataType, ref d._DataType, (i, ev) => i.DataType = ev, v);
                }
                private static void _DataType_Refresh(global::LightSwitchApplication.EntityProperty.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.DataType, ref d._DataType);
                }
                private static void _DataType_OnValueChanged(global::LightSwitchApplication.EntityProperty e)
                {
                    e.DataType_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, global::LightSwitchApplication.Entity>.Entry
                    Entity = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, global::LightSwitchApplication.Entity>.Entry(
                        "Entity",
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._Entity_Stub,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._Entity_ComputeIsReadOnly,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._Entity_Validate,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._Entity_GetCoreImplementationValue,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._Entity_GetImplementationValue,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._Entity_SetImplementationValue,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._Entity_Refresh,
                        global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties._Entity_OnValueChanged);
                private static void _Entity_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EntityProperty.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, global::LightSwitchApplication.Entity>.Data> c, global::LightSwitchApplication.EntityProperty.DetailsClass d, object sf)
                {
                    c(d, ref d._Entity, sf);
                }
                private static bool _Entity_ComputeIsReadOnly(global::LightSwitchApplication.EntityProperty e)
                {
                    bool result = false;
                    e.Entity_IsReadOnly(ref result);
                    return result;
                }
                private static void _Entity_Validate(global::LightSwitchApplication.EntityProperty e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Entity_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Entity_GetCoreImplementationValue(global::LightSwitchApplication.EntityProperty.DetailsClass d)
                {
                    return d.ImplementationEntity.Entity;
                }
                private static global::LightSwitchApplication.Entity _Entity_GetImplementationValue(global::LightSwitchApplication.EntityProperty.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Entity, global::LightSwitchApplication.Entity.DetailsClass>(global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.Entity, ref d._Entity);
                }
                private static void _Entity_SetImplementationValue(global::LightSwitchApplication.EntityProperty.DetailsClass d, global::LightSwitchApplication.Entity v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.Entity, ref d._Entity, (i, ev) => i.Entity = ev, v);
                }
                private static void _Entity_Refresh(global::LightSwitchApplication.EntityProperty.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.EntityProperty.DetailsClass.PropertySetProperties.Entity, ref d._Entity);
                }
                private static void _Entity_OnValueChanged(global::LightSwitchApplication.EntityProperty e)
                {
                    e.Entity_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, string>.Data _PropertyName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, int>.Data _ModelTypeId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, global::LightSwitchApplication.CalculatedProperty>.Data _CalculatedProperty;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, global::LightSwitchApplication.EntityParameter>.Data _EntityParameters;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, global::LightSwitchApplication.DataType>.Data _DataType;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EntityProperty, global::LightSwitchApplication.EntityProperty.DetailsClass, global::LightSwitchApplication.Entity>.Data _Entity;
            
        }
    
        #endregion
    }
    
    #endregion
}
