

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    public sealed partial class c_Operator : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.c_Operator, global::LightSwitchApplication.c_Operator.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the c_Operator entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public c_Operator()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public c_Operator(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.c_Operator> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.c_Operator.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Operator_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Operator_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.c_Operator.DetailsClass.GetValue(this, global::LightSwitchApplication.c_Operator.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.c_Operator.DetailsClass.SetValue(this, global::LightSwitchApplication.c_Operator.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.c_Operator.DetailsClass.GetValue(this, global::LightSwitchApplication.c_Operator.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.c_Operator.DetailsClass.SetValue(this, global::LightSwitchApplication.c_Operator.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.FunctionOperation> FunctionOperations
        {
            get
            {
                return global::LightSwitchApplication.c_Operator.DetailsClass.GetValue(this, global::LightSwitchApplication.c_Operator.DetailsClass.PropertySetProperties.FunctionOperations);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.FunctionOperation> FunctionOperationsQuery
        {
            get
            {
                return global::LightSwitchApplication.c_Operator.DetailsClass.GetQuery(this, global::LightSwitchApplication.c_Operator.DetailsClass.PropertySetProperties.FunctionOperations);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.c_Operator,
                global::LightSwitchApplication.c_Operator.DetailsClass,
                global::LightSwitchApplication.c_Operator.DetailsClass.IImplementation,
                global::LightSwitchApplication.c_Operator.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.c_Operator, global::LightSwitchApplication.c_Operator.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.c_Operator, global::LightSwitchApplication.c_Operator.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.c_Operator.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.c_Operator, global::LightSwitchApplication.c_Operator.DetailsClass>.Entry
                __c_OperatorEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.c_Operator, global::LightSwitchApplication.c_Operator.DetailsClass>.Entry(
                    global::LightSwitchApplication.c_Operator.DetailsClass.__c_Operator_CreateNew,
                    global::LightSwitchApplication.c_Operator.DetailsClass.__c_Operator_Created,
                    global::LightSwitchApplication.c_Operator.DetailsClass.__c_Operator_AllowSaveWithErrors);
            private static global::LightSwitchApplication.c_Operator __c_Operator_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.c_Operator> es)
            {
                return new global::LightSwitchApplication.c_Operator(es);
            }
            private static void __c_Operator_Created(global::LightSwitchApplication.c_Operator e)
            {
                e.c_Operator_Created();
            }
            private static bool __c_Operator_AllowSaveWithErrors(global::LightSwitchApplication.c_Operator e)
            {
                bool result = false;
                e.c_Operator_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.c_Operator, global::LightSwitchApplication.c_Operator.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.c_Operator, global::LightSwitchApplication.c_Operator.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.c_Operator.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.c_Operator, global::LightSwitchApplication.c_Operator.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Operator, global::LightSwitchApplication.c_Operator.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.c_Operator.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Operator, global::LightSwitchApplication.c_Operator.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Operator, global::LightSwitchApplication.c_Operator.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.c_Operator.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Operator, global::LightSwitchApplication.c_Operator.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.c_Operator, global::LightSwitchApplication.c_Operator.DetailsClass, global::LightSwitchApplication.FunctionOperation> FunctionOperations
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.c_Operator.DetailsClass.PropertySetProperties.FunctionOperations) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.c_Operator, global::LightSwitchApplication.c_Operator.DetailsClass, global::LightSwitchApplication.FunctionOperation>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string Name { get; set; }
                new global::System.Collections.IEnumerable FunctionOperations { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Operator, global::LightSwitchApplication.c_Operator.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Operator, global::LightSwitchApplication.c_Operator.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.c_Operator.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.c_Operator.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.c_Operator.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.c_Operator.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.c_Operator.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.c_Operator.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.c_Operator.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Operator, global::LightSwitchApplication.c_Operator.DetailsClass, int>.Data> c, global::LightSwitchApplication.c_Operator.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.c_Operator e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.c_Operator e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.c_Operator.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.c_Operator.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.c_Operator e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Operator, global::LightSwitchApplication.c_Operator.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Operator, global::LightSwitchApplication.c_Operator.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.c_Operator.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.c_Operator.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.c_Operator.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.c_Operator.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.c_Operator.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.c_Operator.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.c_Operator.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Operator, global::LightSwitchApplication.c_Operator.DetailsClass, string>.Data> c, global::LightSwitchApplication.c_Operator.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.c_Operator e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.c_Operator e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.c_Operator.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.c_Operator.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.c_Operator e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.c_Operator, global::LightSwitchApplication.c_Operator.DetailsClass, global::LightSwitchApplication.FunctionOperation>.Entry
                    FunctionOperations = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.c_Operator, global::LightSwitchApplication.c_Operator.DetailsClass, global::LightSwitchApplication.FunctionOperation>.Entry(
                        "FunctionOperations",
                        global::LightSwitchApplication.c_Operator.DetailsClass.PropertySetProperties._FunctionOperations_Stub,
                        global::LightSwitchApplication.c_Operator.DetailsClass.PropertySetProperties._FunctionOperations_GetReferencedEntities,
                        global::LightSwitchApplication.c_Operator.DetailsClass.PropertySetProperties._FunctionOperations_GetEntityCollection);
                private static void _FunctionOperations_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.c_Operator.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.c_Operator, global::LightSwitchApplication.c_Operator.DetailsClass, global::LightSwitchApplication.FunctionOperation>.Data> c, global::LightSwitchApplication.c_Operator.DetailsClass d, object sf)
                {
                    c(d, ref d._FunctionOperations, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.FunctionOperation> _FunctionOperations_GetReferencedEntities(global::LightSwitchApplication.c_Operator.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.FunctionOperation, global::LightSwitchApplication.FunctionOperation.DetailsClass>(global::LightSwitchApplication.c_Operator.DetailsClass.PropertySetProperties.FunctionOperations, ref d._FunctionOperations);
                }
                private static global::System.Collections.IEnumerable _FunctionOperations_GetEntityCollection(global::LightSwitchApplication.c_Operator.DetailsClass d)
                {
                    return d.ImplementationEntity.FunctionOperations;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Operator, global::LightSwitchApplication.c_Operator.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.c_Operator, global::LightSwitchApplication.c_Operator.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.c_Operator, global::LightSwitchApplication.c_Operator.DetailsClass, global::LightSwitchApplication.FunctionOperation>.Data _FunctionOperations;
            
        }
    
        #endregion
    }
    
    #endregion
}
