// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using GenSoft.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class AddinMap
	{
		public static void Map(EntityTypeBuilder<Entities.Addin> entityBuilder)
		{
			entityBuilder.ToTable("Addins", "dbo");
			entityBuilder.HasKey(t => t.Id);
			entityBuilder.Property(t => t.Id).HasColumnName("Id").UseSqlServerIdentityColumn();	
			entityBuilder.Property(t => t.Name).HasColumnName("Name").IsRequired().HasMaxLength(50);
			entityBuilder.Property(t => t.AssemblyName).HasColumnName("AssemblyName").IsRequired().HasMaxLength(50);
		//-------------------Navigation Properties -------------------------------//
				entityBuilder.HasMany(x => x.AddinActions).WithOne(p => p.Addin).HasForeignKey(c => c.AddinId).OnDelete(DeleteBehavior.Restrict);//AddinId//Id//
	
				//----------------Parent Properties
	
		}
	}
}
