// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using GenSoft.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class CalculatedPropertyParameterEntityTypeMap
	{
		public static void Map(EntityTypeBuilder<Entities.CalculatedPropertyParameterEntityType> entityBuilder)
		{
			entityBuilder.ToTable("CalculatedPropertyParameterEntityTypes", "dbo");
			entityBuilder.HasKey(t => t.Id);
			entityBuilder.Property(t => t.Id).HasColumnName("Id").UseSqlServerIdentityColumn();	
			entityBuilder.Property(t => t.CalculatedPropertyParameterId).HasColumnName("CalculatedPropertyParameterId").IsRequired();
			entityBuilder.Property(t => t.EntityTypeAttributeId).HasColumnName("EntityTypeAttributeId").IsRequired();
		//-------------------Navigation Properties -------------------------------//
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.CalculatedPropertyParameter CalculatedPropertyParameter).WithMany(p => p.CalculatedPropertyParameterEntityTypes).HasForeignKey(c => c.CalculatedPropertyParameterId).OnDelete(DeleteBehavior.Restrict);
				//entityBuilder.HasOne(p => p.EntityTypeAttribute EntityTypeAttribute).WithMany(p => p.CalculatedPropertyParameterEntityTypes).HasForeignKey(c => c.EntityTypeAttributeId).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
