// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using GenSoft.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class DBTypeMap
	{
		public static void Map(EntityTypeBuilder<Entities.DBType> entityBuilder)
		{
			entityBuilder.ToTable("DBType", "dbo");
			entityBuilder.HasKey(t => t.Id);
			entityBuilder.Property(t => t.Id).HasColumnName("Id").ValueGeneratedNever();	
			entityBuilder.Property(t => t.Id).HasColumnName("Id").IsRequired();
			entityBuilder.Property(t => t.Schema).HasColumnName("Schema").IsRequired().HasMaxLength(50);
			entityBuilder.Property(t => t.Table).HasColumnName("Table").IsRequired().HasMaxLength(50);
		//-------------------Navigation Properties -------------------------------//
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.EntityType EntityType).WithOne(p => p.DBType).HasForeignKey<EntityType>(c => c.Id).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
