// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using GenSoft.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class Document_TypeMap
	{
		public static void Map(EntityTypeBuilder<Entities.Document_Type> entityBuilder)
		{
			entityBuilder.ToTable("Document_Type", "dbo");
			entityBuilder.HasKey(t => t.Id);
			entityBuilder.Property(t => t.Id).HasColumnName("Id").UseSqlServerIdentityColumn();	
			entityBuilder.Property(t => t.DeclarationGenProcedureCodeId).HasColumnName("DeclarationGenProcedureCodeId").IsRequired();
			entityBuilder.Property(t => t.TypeOfDeclarationId).HasColumnName("TypeOfDeclarationId").IsRequired();
		//-------------------Navigation Properties -------------------------------//
				entityBuilder.HasMany(x => x.Customs_Procedure).WithOne(p => p.Document_Type).HasForeignKey(c => c.DocumentTypeId).OnDelete(DeleteBehavior.Restrict);
				entityBuilder.HasMany(x => x.xcuda_ASYCUDA_ExtendedProperties).WithOne(p => p.Document_Type).HasForeignKey(c => c.Document_TypeId).OnDelete(DeleteBehavior.Restrict);
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.DeclarationCode DeclarationCode).WithMany(p => p.Document_Type).HasForeignKey(c => c.DeclarationGenProcedureCodeId).OnDelete(DeleteBehavior.Restrict);
				//entityBuilder.HasOne(p => p.DeclarationType DeclarationType).WithMany(p => p.Document_Type).HasForeignKey(c => c.TypeOfDeclarationId).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
