// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using GenSoft.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class EntityViewModelSetsMap
	{
		public static void Map(EntityTypeBuilder<Entities.EntityViewModelSets> entityBuilder)
		{
			entityBuilder.ToTable("EntityViewModelSets", "dbo");
			entityBuilder.HasKey(t => t.Id);
			entityBuilder.Property(t => t.Id).HasColumnName("Id").UseSqlServerIdentityColumn();	
			entityBuilder.Property(t => t.ParentViewModelId).HasColumnName("ParentViewModelId").IsRequired();
			entityBuilder.Property(t => t.ChildViewModelId).HasColumnName("ChildViewModelId").IsRequired();
		//-------------------Navigation Properties -------------------------------//
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.EntityTypeViewModel ParentViewModel).WithMany(p => p.EntityViewModelSets).HasForeignKey(c => c.ParentViewModelId).OnDelete(DeleteBehavior.Restrict);
				//entityBuilder.HasOne(p => p.EntityTypeViewModel ChildViewModel).WithMany(p => p.EntityViewModelSets).HasForeignKey(c => c.ChildViewModelId).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
