// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using GenSoft.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class EntityAttributeChangesMap
	{
		public static void Map(EntityTypeBuilder<Entities.EntityAttributeChanges> entityBuilder)
		{
			entityBuilder.ToTable("EntityAttributeChanges", "dbo");
			entityBuilder.HasKey(t => t.Id);
			entityBuilder.Property(t => t.Id).HasColumnName("Id").UseSqlServerIdentityColumn();	
			entityBuilder.Property(t => t.PredecessorId).HasColumnName("PredecessorId").IsRequired();
			entityBuilder.Property(t => t.EntryDateTime).HasColumnName("EntryDateTime").IsRequired();
			entityBuilder.Property(t => t.SuccessorId).HasColumnName("SuccessorId").IsRequired();
		//-------------------Navigation Properties -------------------------------//
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.EntityAttribute Predecessor).WithMany(p => p.EntityAttributeChanges).HasForeignKey(c => c.PredecessorId).OnDelete(DeleteBehavior.Restrict);
				//entityBuilder.HasOne(p => p.EntityAttribute Successor).WithMany(p => p.EntityAttributeChanges).HasForeignKey(c => c.SuccessorId).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
