// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class EventPredicatesMap
	{
		public static void Map(EntityTypeBuilder<Entities.EventPredicates> entityBuilder)
		{
			entityBuilder.ToTable("EventPredicates", "dbo");
			entityBuilder.HasKey(t => t.Id);
			entityBuilder.Property(t => t.Id).HasColumnName("Id").UseSqlServerIdentityColumn();	
			entityBuilder.Property(t => t.EventTypeId).HasColumnName("EventTypeId").IsRequired();
			entityBuilder.Property(t => t.PredicateId).HasColumnName("PredicateId").IsRequired();
		//-------------------Navigation Properties -------------------------------//
				entityBuilder.HasMany(x => x.ExpectedEventPredicateParameters).WithOne(p => p.EventPredicates).HasForeignKey(c => c.EventPredicateId).OnDelete(DeleteBehavior.Restrict);
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.EventType EventType).WithMany(p => p.EventPredicates).HasForeignKey(c => c.EventTypeId).OnDelete(DeleteBehavior.Restrict);
				//entityBuilder.HasOne(p => p.Predicates Predicates).WithMany(p => p.EventPredicates).HasForeignKey(c => c.PredicateId).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
