// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class ExpectedStateEventInfoMap
	{
		public static void Map(EntityTypeBuilder<Entities.ExpectedStateEventInfo> entityBuilder)
		{
			entityBuilder.ToTable("ExpectedStateEventInfo", "dbo");
			entityBuilder.HasKey(t => t.Id);
			entityBuilder.Property(t => t.Id).HasColumnName("Id").ValueGeneratedNever();	
			entityBuilder.Property(t => t.Id).HasColumnName("Id").IsRequired();
			entityBuilder.Property(t => t.ExpectedStateEventInfoId).HasColumnName("ExpectedStateEventInfoId").IsRequired();
		//-------------------Navigation Properties -------------------------------//
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.StateCommandInfo StateCommandInfo).WithOne(p => p.ExpectedStateEventInfo).HasForeignKey<StateCommandInfo>(c => c.Id).OnDelete(DeleteBehavior.Restrict);
				//entityBuilder.HasOne(p => p.StateEventInfo StateEventInfo).WithMany(p => p.ExpectedStateEventInfo).HasForeignKey(c => c.ExpectedStateEventInfoId).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
