// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class MainEntityMap
	{
		public static void Map(EntityTypeBuilder<Entities.MainEntity> entityBuilder)
		{
			entityBuilder.ToTable("MainEntity", "dbo");
			entityBuilder.HasKey(t => t.Id);
			entityBuilder.Property(t => t.Id).HasColumnName("Id").ValueGeneratedNever();	
			entityBuilder.Property(t => t.EntityTypeId).HasColumnName("EntityTypeId").IsRequired();
			entityBuilder.Property(t => t.Id).HasColumnName("Id").IsRequired();
		//-------------------Navigation Properties -------------------------------//
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.EntityType EntityType).WithMany(p => p.MainEntity).HasForeignKey(c => c.EntityTypeId).OnDelete(DeleteBehavior.Restrict);
				//entityBuilder.HasOne(p => p.ProcessStep ProcessStep).WithOne(p => p.MainEntity).HasForeignKey<ProcessStep>(c => c.Id).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
