// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using GenSoft.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class OrdinalityMap
	{
		public static void Map(EntityTypeBuilder<Entities.Ordinality> entityBuilder)
		{
			entityBuilder.ToTable("Ordinality", "dbo");
			entityBuilder.HasKey(t => t.Id);
			entityBuilder.Property(t => t.Id).HasColumnName("Id").UseSqlServerIdentityColumn();	
			entityBuilder.Property(t => t.Name).HasColumnName("Name").IsRequired().HasMaxLength(50);
		//-------------------Navigation Properties -------------------------------//
				entityBuilder.HasMany(x => x.ChildOrdinalitys).WithOne(p => p.ChildOrdinalitys).HasForeignKey(c => c.ChildOrdinalityId).OnDelete(DeleteBehavior.Restrict);
				entityBuilder.HasMany(x => x.ParentOrdinalitys).WithOne(p => p.ParentOrdinalitys).HasForeignKey(c => c.ParentOrdinalityId).OnDelete(DeleteBehavior.Restrict);
	
				//----------------Parent Properties
	
		}
	}
}
