// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using GenSoft.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class ProcessMap
	{
		public static void Map(EntityTypeBuilder<Entities.Process> entityBuilder)
		{
			entityBuilder.ToTable("Process", "dbo");
			entityBuilder.HasKey(t => t.Id);
			entityBuilder.Property(t => t.Id).HasColumnName("Id").UseSqlServerIdentityColumn();	
			entityBuilder.Property(t => t.Name).HasColumnName("Name").IsRequired().HasMaxLength(Int32.MaxValue);
			entityBuilder.Property(t => t.Description).HasColumnName("Descripton").IsRequired().HasMaxLength(255);
		//-------------------Navigation Properties -------------------------------//
				entityBuilder.HasOne(p => p.DomainProcess).WithOne(p => p.Process).HasForeignKey<DomainProcess>(c => c.Id).OnDelete(DeleteBehavior.Restrict);
				entityBuilder.HasOne(p => p.SystemProcess).WithOne(p => p.Process).HasForeignKey<SystemProcess>(c => c.Id).OnDelete(DeleteBehavior.Restrict);
	
				//----------------Parent Properties
	
		}
	}
}
