// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using GenSoft.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class ProcessMap
	{
		public static void Map(EntityTypeBuilder<Entities.Process> entityBuilder)
		{
			entityBuilder.ToTable("Process", "dbo");
			entityBuilder.HasKey(t => t.Id);
			entityBuilder.Property(t => t.Id).HasColumnName("Id").UseSqlServerIdentityColumn();	
			entityBuilder.Property(t => t.UserId).HasColumnName("UserId").IsRequired();
			entityBuilder.Property(t => t.Description).HasColumnName("Description").IsRequired().HasMaxLength(Int32.MaxValue);
			entityBuilder.Property(t => t.Name).HasColumnName("Name").IsRequired().HasMaxLength(Int32.MaxValue);
			entityBuilder.Property(t => t.ParentProcessId).HasColumnName("ParentProcessId").IsRequired();
			entityBuilder.Property(t => t.Symbol).HasColumnName("Symbol").IsRequired().HasMaxLength(Int32.MaxValue);
		//-------------------Navigation Properties -------------------------------//
				entityBuilder.HasMany(x => x.Message).WithOne(p => p.Process).HasForeignKey(c => c.ProcessId).OnDelete(DeleteBehavior.Restrict);
				entityBuilder.HasMany(x => x.MessageSource).WithOne(p => p.Process).HasForeignKey(c => c.ProcessId).OnDelete(DeleteBehavior.Restrict);
				entityBuilder.HasMany(x => x.ProcessState).WithOne(p => p.Process).HasForeignKey(c => c.ProcessId).OnDelete(DeleteBehavior.Restrict);
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.Agent Agent).WithMany(p => p.Process).HasForeignKey(c => c.UserId).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
