// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using GenSoft.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class ProcessActionStateCommandInfoMap
	{
		public static void Map(EntityTypeBuilder<Entities.ProcessActionStateCommandInfo> entityBuilder)
		{
			entityBuilder.ToTable("ProcessActionStateCommandInfo", "dbo");
			entityBuilder.HasKey(t => t.Id);
			entityBuilder.Property(t => t.Id).HasColumnName("Id").ValueGeneratedNever();	
			entityBuilder.Property(t => t.Id).HasColumnName("Id").IsRequired();
			entityBuilder.Property(t => t.StateComandInfoId).HasColumnName("StateComandInfoId").IsRequired();
		//-------------------Navigation Properties -------------------------------//
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.ProcessAction ProcessAction).WithOne(p => p.ProcessActionStateCommandInfo).HasForeignKey<ProcessAction>(c => c.Id).OnDelete(DeleteBehavior.Restrict);
				//entityBuilder.HasOne(p => p.StateCommandInfo StateCommandInfo).WithMany(p => p.ProcessActionStateCommandInfo).HasForeignKey(c => c.StateComandInfoId).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
