// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using GenSoft.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class ProcessActionMap
	{
		public static void Map(EntityTypeBuilder<Entities.ProcessAction> entityBuilder)
		{
			entityBuilder.ToTable("ProcessAction", "dbo");
			entityBuilder.HasKey(t => t.Id);
			entityBuilder.Property(t => t.Id).HasColumnName("Id").UseSqlServerIdentityColumn();	
			entityBuilder.Property(t => t.ActionSetId).HasColumnName("ActionSetId").IsRequired();
			entityBuilder.Property(t => t.Name).HasColumnName("Name").IsRequired().HasMaxLength(50);
			entityBuilder.Property(t => t.StateComandInfoId).HasColumnName("StateComandInfoId").IsRequired();
		//-------------------Navigation Properties -------------------------------//
				entityBuilder.HasMany(x => x.ComplexEventActionProcessActions).WithOne(p => p.ProcessAction).HasForeignKey(c => c.ProcessActionId).OnDelete(DeleteBehavior.Restrict);
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.ActionSet ActionSet).WithMany(p => p.ProcessAction).HasForeignKey(c => c.ActionSetId).OnDelete(DeleteBehavior.Restrict);
				//entityBuilder.HasOne(p => p.StateCommandInfo StateCommandInfo).WithMany(p => p.ProcessAction).HasForeignKey(c => c.StateComandInfoId).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
