// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class ReferenceTypeNameMap
	{
		public static void Map(EntityTypeBuilder<Entities.ReferenceTypeName> entityBuilder)
		{
			entityBuilder.ToTable("ReferenceTypeName", "dbo");
			entityBuilder.HasKey(t => t.Id);
			entityBuilder.Property(t => t.Id).HasColumnName("Id").ValueGeneratedNever();	
			entityBuilder.Property(t => t.Id).HasColumnName("Id").IsRequired();
			entityBuilder.Property(t => t.Name).HasColumnName("Name").IsRequired().HasMaxLength(50);
		//-------------------Navigation Properties -------------------------------//
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.ReferenceTypes ReferenceTypes).WithOne(p => p.ReferenceTypeName).HasForeignKey<ReferenceTypes>(c => c.Id).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
