// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using GenSoft.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class StateActionMap
	{
		public static void Map(EntityTypeBuilder<Entities.StateAction> entityBuilder)
		{
			entityBuilder.ToTable("StateAction", "dbo");
			entityBuilder.HasKey(t => t.Id);
			entityBuilder.Property(t => t.Id).HasColumnName("Id").UseSqlServerIdentityColumn();	
			entityBuilder.Property(t => t.ActionSetId).HasColumnName("ActionSetId").IsRequired();
			entityBuilder.Property(t => t.ProcessStateId).HasColumnName("ProcessStateId").IsRequired();
		//-------------------Navigation Properties -------------------------------//
				entityBuilder.HasMany(x => x.Command).WithOne(p => p.StateAction).HasForeignKey(c => c.StateActionId).OnDelete(DeleteBehavior.Restrict);
				entityBuilder.HasOne(p => p.StateActionExpectedProcessState).WithOne(p => p.StateAction).HasForeignKey<StateActionExpectedProcessState>(c => c.Id).OnDelete(DeleteBehavior.Restrict);
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.ActionSet ActionSet).WithMany(p => p.StateAction).HasForeignKey(c => c.ActionSetId).OnDelete(DeleteBehavior.Restrict);
				//entityBuilder.HasOne(p => p.ProcessState ProcessState).WithMany(p => p.StateAction).HasForeignKey(c => c.ProcessStateId).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
