// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using GenSoft.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class StateInfoMap
	{
		public static void Map(EntityTypeBuilder<Entities.StateInfo> entityBuilder)
		{
			entityBuilder.ToTable("StateInfo", "dbo");
			entityBuilder.HasKey(t => t.Id);
			entityBuilder.Property(t => t.Id).HasColumnName("Id").UseSqlServerIdentityColumn();	
			entityBuilder.Property(t => t.Name).HasColumnName("Name").IsRequired().HasMaxLength(50);
			entityBuilder.Property(t => t.Status).HasColumnName("Status").IsRequired().HasMaxLength(255);
			entityBuilder.Property(t => t.Subject).HasColumnName("Subject").IsRequired().HasMaxLength(50);
		//-------------------Navigation Properties -------------------------------//
				entityBuilder.HasOne(p => p.StateCommandInfo).WithOne(p => p.StateInfo).HasForeignKey<StateCommandInfo>(c => c.Id).OnDelete(DeleteBehavior.Restrict);
				entityBuilder.HasOne(p => p.StateEventInfo).WithOne(p => p.StateInfo).HasForeignKey<StateEventInfo>(c => c.Id).OnDelete(DeleteBehavior.Restrict);
				entityBuilder.HasOne(p => p.StateInfoNotes).WithOne(p => p.StateInfo).HasForeignKey<StateInfoNotes>(c => c.Id).OnDelete(DeleteBehavior.Restrict);
	
				//----------------Parent Properties
	
		}
	}
}
