// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using GenSoft.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class SubItemsMap
	{
		public static void Map(EntityTypeBuilder<Entities.SubItems> entityBuilder)
		{
			entityBuilder.ToTable("SubItems", "dbo");
			entityBuilder.HasKey(t => t.SubItem_Id);
			entityBuilder.Property(t => t.SubItem_Id).HasColumnName("SubItem_Id").UseSqlServerIdentityColumn();	
			entityBuilder.Property(t => t.Item_Id).HasColumnName("Item_Id").IsRequired();
			entityBuilder.Property(t => t.ItemDescription).HasColumnName("ItemDescription").IsRequired().HasMaxLength(Int32.MaxValue);
			entityBuilder.Property(t => t.ItemNumber).HasColumnName("ItemNumber").IsRequired().HasMaxLength(50);
			entityBuilder.Property(t => t.QtyAllocated).HasColumnName("QtyAllocated").IsRequired();
			entityBuilder.Property(t => t.Quantity).HasColumnName("Quantity").IsRequired();
		//-------------------Navigation Properties -------------------------------//
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.xcuda_Item xcuda_Item).WithMany(p => p.SubItems).HasForeignKey(c => c.Item_Id).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
