// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using GenSoft.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class xcuda_ExportMap
	{
		public static void Map(EntityTypeBuilder<Entities.xcuda_Export> entityBuilder)
		{
			entityBuilder.ToTable("xcuda_Export", "dbo");
			entityBuilder.HasKey(t => t.Country_Id);
			entityBuilder.Property(t => t.Country_Id).HasColumnName("Country_Id").ValueGeneratedNever();	
			entityBuilder.Property(t => t.Country_Id).HasColumnName("Country_Id").IsRequired();
			entityBuilder.Property(t => t.Export_country_code).HasColumnName("Export_country_code").IsRequired().HasMaxLength(50);
			entityBuilder.Property(t => t.Export_country_name).HasColumnName("Export_country_name").IsRequired().HasMaxLength(50);
			entityBuilder.Property(t => t.Export_country_name).HasColumnName("Export_country_name").IsRequired().HasMaxLength(50);
			entityBuilder.Property(t => t.Export_country_region).HasColumnName("Export_country_region").IsRequired().HasMaxLength(50);
		//-------------------Navigation Properties -------------------------------//
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.xcuda_Country xcuda_Country).WithOne(p => p.xcuda_Export).HasForeignKey<xcuda_Country>(c => c.Country_Id).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
