// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using GenSoft.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class xcuda_Means_of_transportMap
	{
		public static void Map(EntityTypeBuilder<Entities.xcuda_Means_of_transport> entityBuilder)
		{
			entityBuilder.ToTable("xcuda_Means_of_transport", "dbo");
			entityBuilder.HasKey(t => t.Means_of_transport_Id);
			entityBuilder.Property(t => t.Means_of_transport_Id).HasColumnName("Means_of_transport_Id").UseSqlServerIdentityColumn();	
			entityBuilder.Property(t => t.Inland_mode_of_transport).HasColumnName("Inland_mode_of_transport").IsRequired().HasMaxLength(50);
			entityBuilder.Property(t => t.Transport_Id).HasColumnName("Transport_Id").IsRequired();
		//-------------------Navigation Properties -------------------------------//
				entityBuilder.HasMany(x => x.xcuda_Border_information).WithOne(p => p.xcuda_Means_of_transport).HasForeignKey(c => c.Means_of_transport_Id).OnDelete(DeleteBehavior.Restrict);
				entityBuilder.HasMany(x => x.xcuda_Departure_arrival_information).WithOne(p => p.xcuda_Means_of_transport).HasForeignKey(c => c.Means_of_transport_Id).OnDelete(DeleteBehavior.Restrict);
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.xcuda_Transport xcuda_Transport).WithMany(p => p.xcuda_Means_of_transport).HasForeignKey(c => c.Transport_Id).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
