// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using GenSoft.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class xcuda_Traders_FinancialMap
	{
		public static void Map(EntityTypeBuilder<Entities.xcuda_Traders_Financial> entityBuilder)
		{
			entityBuilder.ToTable("xcuda_Traders_Financial", "dbo");
			entityBuilder.HasKey(t => t.Traders_Id);
			entityBuilder.Property(t => t.Traders_Id).HasColumnName("Traders_Id").ValueGeneratedNever();	
			entityBuilder.Property(t => t.Traders_Id).HasColumnName("Traders_Id").IsRequired();
			entityBuilder.Property(t => t.Financial_code).HasColumnName("Financial_code").IsRequired().HasMaxLength(Int32.MaxValue);
			entityBuilder.Property(t => t.Financial_name).HasColumnName("Financial_name").IsRequired().HasMaxLength(Int32.MaxValue);
			entityBuilder.Property(t => t.Financial_name).HasColumnName("Financial_name").IsRequired().HasMaxLength(Int32.MaxValue);
		//-------------------Navigation Properties -------------------------------//
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.xcuda_Traders xcuda_Traders).WithOne(p => p.xcuda_Traders_Financial).HasForeignKey<xcuda_Traders>(c => c.Traders_Id).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
