// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using GenSoft.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class xcuda_PackagesMap
	{
		public static void Map(EntityTypeBuilder<Entities.xcuda_Packages> entityBuilder)
		{
			entityBuilder.ToTable("xcuda_Packages", "dbo");
			entityBuilder.HasKey(t => t.Packages_Id);
			entityBuilder.Property(t => t.Packages_Id).HasColumnName("Packages_Id").UseSqlServerIdentityColumn();	
			entityBuilder.Property(t => t.Item_Id).HasColumnName("Item_Id").IsRequired();
			entityBuilder.Property(t => t.Kind_of_packages_code).HasColumnName("Kind_of_packages_code").IsRequired().HasMaxLength(Int32.MaxValue);
			entityBuilder.Property(t => t.Kind_of_packages_name).HasColumnName("Kind_of_packages_name").IsRequired().HasMaxLength(Int32.MaxValue);
			entityBuilder.Property(t => t.Kind_of_packages_name).HasColumnName("Kind_of_packages_name").IsRequired().HasMaxLength(Int32.MaxValue);
			entityBuilder.Property(t => t.Marks1_of_packages).HasColumnName("Marks1_of_packages").IsRequired().HasMaxLength(Int32.MaxValue);
			entityBuilder.Property(t => t.Marks2_of_packages).HasColumnName("Marks2_of_packages").IsRequired().HasMaxLength(Int32.MaxValue);
			entityBuilder.Property(t => t.Number_of_packages).HasColumnName("Number_of_packages").IsRequired();
		//-------------------Navigation Properties -------------------------------//
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.xcuda_Item xcuda_Item).WithMany(p => p.xcuda_Packages).HasForeignKey(c => c.Item_Id).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
