// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using GenSoft.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class xcuda_Global_taxesMap
	{
		public static void Map(EntityTypeBuilder<Entities.xcuda_Global_taxes> entityBuilder)
		{
			entityBuilder.ToTable("xcuda_Global_taxes", "dbo");
			entityBuilder.HasKey(t => t.Global_taxes_Id);
			entityBuilder.Property(t => t.Global_taxes_Id).HasColumnName("Global_taxes_Id").UseSqlServerIdentityColumn();	
			entityBuilder.Property(t => t.ASYCUDA_Id).HasColumnName("ASYCUDA_Id").IsRequired();
		//-------------------Navigation Properties -------------------------------//
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.xcuda_ASYCUDA xcuda_ASYCUDA).WithMany(p => p.xcuda_Global_taxes).HasForeignKey(c => c.ASYCUDA_Id).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
