// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using GenSoft.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class xcuda_Financial_GuaranteeMap
	{
		public static void Map(EntityTypeBuilder<Entities.xcuda_Financial_Guarantee> entityBuilder)
		{
			entityBuilder.ToTable("xcuda_Financial_Guarantee", "dbo");
			entityBuilder.HasKey(t => t.Guarantee_Id);
			entityBuilder.Property(t => t.Guarantee_Id).HasColumnName("Guarantee_Id").UseSqlServerIdentityColumn();	
			entityBuilder.Property(t => t.Financial_Id).HasColumnName("Financial_Id").IsRequired();
			entityBuilder.Property(t => t.Date).HasColumnName("Date").IsRequired();
		//-------------------Navigation Properties -------------------------------//
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.xcuda_Financial xcuda_Financial).WithMany(p => p.xcuda_Financial_Guarantee).HasForeignKey(c => c.Financial_Id).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
