// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using GenSoft.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class xcuda_TradersMap
	{
		public static void Map(EntityTypeBuilder<Entities.xcuda_Traders> entityBuilder)
		{
			entityBuilder.ToTable("xcuda_Traders", "dbo");
			entityBuilder.HasKey(t => t.Traders_Id);
			entityBuilder.Property(t => t.Traders_Id).HasColumnName("Traders_Id").ValueGeneratedNever();	
			entityBuilder.Property(t => t.Traders_Id).HasColumnName("Traders_Id").IsRequired();
		//-------------------Navigation Properties -------------------------------//
				entityBuilder.HasOne(p => p.xcuda_Consignee).WithOne(p => p.xcuda_Traders).HasForeignKey<xcuda_Consignee>(c => c.Traders_Id).OnDelete(DeleteBehavior.Restrict);
				entityBuilder.HasOne(p => p.xcuda_Exporter).WithOne(p => p.xcuda_Traders).HasForeignKey<xcuda_Exporter>(c => c.Traders_Id).OnDelete(DeleteBehavior.Restrict);
				entityBuilder.HasOne(p => p.xcuda_Traders_Financial).WithOne(p => p.xcuda_Traders).HasForeignKey<xcuda_Traders_Financial>(c => c.Traders_Id).OnDelete(DeleteBehavior.Restrict);
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.xcuda_ASYCUDA xcuda_ASYCUDA).WithOne(p => p.xcuda_Traders).HasForeignKey<xcuda_ASYCUDA>(c => c.Traders_Id).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
