// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using GenSoft.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class xcuda_PropertyMap
	{
		public static void Map(EntityTypeBuilder<Entities.xcuda_Property> entityBuilder)
		{
			entityBuilder.ToTable("xcuda_Property", "dbo");
			entityBuilder.HasKey(t => t.ASYCUDA_Id);
			entityBuilder.Property(t => t.ASYCUDA_Id).HasColumnName("ASYCUDA_Id").ValueGeneratedNever();	
			entityBuilder.Property(t => t.ASYCUDA_Id).HasColumnName("ASYCUDA_Id").IsRequired();
			entityBuilder.Property(t => t.Date_of_declaration).HasColumnName("Date_of_declaration").IsRequired().HasMaxLength(Int32.MaxValue);
			entityBuilder.Property(t => t.Place_of_declaration).HasColumnName("Place_of_declaration").IsRequired().HasMaxLength(Int32.MaxValue);
			entityBuilder.Property(t => t.Sad_flow).HasColumnName("Sad_flow").IsRequired().HasMaxLength(Int32.MaxValue);
			entityBuilder.Property(t => t.Selected_page).HasColumnName("Selected_page").IsRequired().HasMaxLength(Int32.MaxValue);
		//-------------------Navigation Properties -------------------------------//
				entityBuilder.HasOne(p => p.xcuda_Forms).WithOne(p => p.xcuda_Property).HasForeignKey<xcuda_Forms>(c => c.ASYCUDA_Id).OnDelete(DeleteBehavior.Restrict);
				entityBuilder.HasOne(p => p.xcuda_Nbers).WithOne(p => p.xcuda_Property).HasForeignKey<xcuda_Nbers>(c => c.ASYCUDA_Id).OnDelete(DeleteBehavior.Restrict);
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.xcuda_ASYCUDA xcuda_ASYCUDA).WithOne(p => p.xcuda_Property).HasForeignKey<xcuda_ASYCUDA>(c => c.ASYCUDA_Id).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
