// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using GenSoft.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class xcuda_Border_informationMap
	{
		public static void Map(EntityTypeBuilder<Entities.xcuda_Border_information> entityBuilder)
		{
			entityBuilder.ToTable("xcuda_Border_information", "dbo");
			entityBuilder.HasKey(t => t.Border_information_Id);
			entityBuilder.Property(t => t.Border_information_Id).HasColumnName("Border_information_Id").UseSqlServerIdentityColumn();	
			entityBuilder.Property(t => t.Identity).HasColumnName("Identity").IsRequired().HasMaxLength(50);
			entityBuilder.Property(t => t.Means_of_transport_Id).HasColumnName("Means_of_transport_Id").IsRequired();
			entityBuilder.Property(t => t.Mode).HasColumnName("Mode").IsRequired();
			entityBuilder.Property(t => t.Nationality).HasColumnName("Nationality").IsRequired().HasMaxLength(50);
		//-------------------Navigation Properties -------------------------------//
	
				//----------------Parent Properties
				//entityBuilder.HasOne(p => p.xcuda_Means_of_transport xcuda_Means_of_transport).WithMany(p => p.xcuda_Border_information).HasForeignKey(c => c.Means_of_transport_Id).OnDelete(DeleteBehavior.Restrict);
	
		}
	}
}
