// <autogenerated>
//   This file was generated by T4 code generator MRManger-Interfaces.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using SystemInterfaces;
using System.ComponentModel.Composition;
using GenSoft.Interfaces;

namespace GenSoft.Interfaces
{
	
	public partial interface IProcessInfo:IEntityView<IAgent>
	{
		string UserName { get;}



	}
}
